<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Kor.Operations.Rendering</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.18.0" />
    <PackageReference Include="PDFsharp-WPF" Version="6.2.4" />
    <PackageReference Include="QuestPDF" Version="2026.2.3" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.556">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Kor.Operations.Core\Kor.Operations.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Fonts\Mulish\Mulish-Regular.ttf" />
    <EmbeddedResource Include="Fonts\Mulish\Mulish-Bold.ttf" />
    <EmbeddedResource Include="Fonts\Mulish\Mulish-Italic.ttf" />
    <EmbeddedResource Include="Fonts\Mulish\Mulish-BoldItalic.ttf" />
    <EmbeddedResource Include="Fonts\Mulish\Mulish-Black.ttf" />
  </ItemGroup>
</Project>
