// THE VERBS, IN THE ORDER PROGRAM.CS TRIED THEM (WP3, 2026-09-11): a usage pre-check for a verb sits
// before the verb, as it did. Program.cs asks each in turn; the first that matches runs.
public static class TakeoffVerbs
{
    public static readonly IReadOnlyList<(string Name, Func<string[], bool> Matches, Func<string[], int> Run)> All =
    [
        ("estimate", EstimateUsageVerb.Matches, EstimateUsageVerb.Run),
        ("measure", MeasureUsageVerb.Matches, MeasureUsageVerb.Run),
        ("vision-estimate", VisionEstimateUsageVerb.Matches, VisionEstimateUsageVerb.Run),
        ("pdf-readable", PdfReadableVerb.Matches, PdfReadableVerb.Run),
        ("pdf-takeoff", PdfTakeoffVerb.Matches, PdfTakeoffVerb.Run),
        ("dxf-census", DxfCensusVerb.Matches, DxfCensusVerb.Run),
        ("corpus-census", CorpusCensusVerb.Matches, CorpusCensusVerb.Run),
        ("model-render", ModelRenderVerb.Matches, ModelRenderVerb.Run),
        ("model-diff", ModelDiffVerb.Matches, ModelDiffVerb.Run),
        ("model-yardstick", ModelYardstickVerb.Matches, ModelYardstickVerb.Run),
        ("grid-names", GridNamesVerb.Matches, GridNamesVerb.Run),
        ("model-to-page", ModelToPageVerb.Matches, ModelToPageVerb.Run),
        ("model-at", ModelAtVerb.Matches, ModelAtVerb.Run),
        ("pdf-at", PdfAtVerb.Matches, PdfAtVerb.Run),
        ("corpus-analyze", CorpusAnalyzeVerb.Matches, CorpusAnalyzeVerb.Run),
        ("corpus-query", CorpusQueryVerb.Matches, CorpusQueryVerb.Run),
        ("corpus-disagreements", a => a.Length >= 1 && a[0].Equals("corpus-disagreements", StringComparison.OrdinalIgnoreCase), CorpusDisagreementsVerb.Run),
        ("corpus-ledger-db", CorpusLedgerDbVerb.Matches, CorpusLedgerDbVerb.Run),
        ("pdf-levels", PdfLevelsVerb.Matches, PdfLevelsVerb.Run),
        ("pdf-assemblies", PdfAssembliesVerb.Matches, PdfAssembliesVerb.Run),
        ("storeys-check", StoreysCheckVerb.Matches, StoreysCheckVerb.Run),
        ("intake-baseline", IntakeBaselineVerb.Matches, IntakeBaselineVerb.Run),
        ("markup-list", MarkupListVerb.Matches, MarkupListVerb.Run),
        ("set-check", SetCheckVerb.Matches, SetCheckVerb.Run),
        ("markup-reconcile", MarkupReconcileVerb.Matches, MarkupReconcileVerb.Run),
        ("set-diff", SetDiffVerb.Matches, SetDiffVerb.Run),
        ("pdf-inventory", PdfInventoryVerb.Matches, PdfInventoryVerb.Run),
        ("pdf-overlay", PdfOverlayVerb.Matches, PdfOverlayVerb.Run),
        ("pdf-vs-dxf", PdfVsDxfVerb.Matches, PdfVsDxfVerb.Run),
        ("dxf-render", DxfRenderVerb.Matches, DxfRenderVerb.Run),
        ("verify-e2k", VerifyE2kVerb.Matches, VerifyE2kVerb.Run),
        ("e2k-multiset", E2kMultisetVerb.Matches, E2kMultisetVerb.Run),
        ("dxf-inspect", DxfInspectVerb.Matches, DxfInspectVerb.Run),
        ("dxf-strip", DxfStripVerb.Matches, DxfStripVerb.Run),
        ("publish", PublishVerb.Matches, PublishVerb.Run),
        ("dxf-buildings", DxfBuildingsVerb.Matches, DxfBuildingsVerb.Run),
        ("e2k-compare", E2kCompareVerb.Matches, E2kCompareVerb.Run),
        ("dxf-import-rules", DxfImportRulesVerb.Matches, DxfImportRulesVerb.Run),
        ("corpus-read", CorpusReadVerb.Matches, CorpusReadVerb.Run),
        ("dxf-to-etabs", DxfToEtabsVerb.Matches, DxfToEtabsVerb.Run),
        ("ifc-takeoff", IfcTakeoffVerb.Matches, IfcTakeoffVerb.Run),
        ("revit-takeoff", RevitTakeoffVerb.Matches, RevitTakeoffVerb.Run),
        ("sco-schedule", ScoScheduleVerb.Matches, ScoScheduleVerb.Run),
        ("e2k-ask", E2kAskVerb.Matches, E2kAskVerb.Run),
        ("e2k-takeoff", E2kTakeoffVerb.Matches, E2kTakeoffVerb.Run),
        ("vector-takeoff", VectorTakeoffVerb.Matches, VectorTakeoffVerb.Run),
        ("vector-plate", VectorPlateVerb.Matches, VectorPlateVerb.Run),
        ("vector-zones", VectorZonesVerb.Matches, VectorZonesVerb.Run),
        ("vector-synth", VectorSynthVerb.Matches, VectorSynthVerb.Run),
        ("vector-digest", VectorDigestVerb.Matches, VectorDigestVerb.Run),
        ("vector-sched", VectorSchedVerb.Matches, VectorSchedVerb.Run),
        ("sched-border", SchedBorderVerb.Matches, SchedBorderVerb.Run),
        ("vector-dump", VectorDumpVerb.Matches, VectorDumpVerb.Run),
        ("vector-plate-auto", VectorPlateAutoVerb.Matches, VectorPlateAutoVerb.Run),
        ("vector-geom", VectorGeomVerb.Matches, VectorGeomVerb.Run),
        ("vector-signals", VectorSignalsVerb.Matches, VectorSignalsVerb.Run),
        ("scale-scan", ScaleScanVerb.Matches, ScaleScanVerb.Run),
        ("vector-words", VectorWordsVerb.Matches, VectorWordsVerb.Run),
        ("vector-lines", VectorLinesVerb.Matches, VectorLinesVerb.Run),
        ("vector-find", VectorFindVerb.Matches, VectorFindVerb.Run),
        ("vision-estimate", VisionEstimateVerb.Matches, VisionEstimateVerb.Run),
        ("estimate", EstimateVerb.Matches, EstimateVerb.Run),
        ("measure", MeasureVerb.Matches, MeasureVerb.Run),
        ("graycomp", GraycompVerb.Matches, GraycompVerb.Run),
        ("hatch", HatchVerb.Matches, HatchVerb.Run),
        ("wallsched", WallschedVerb.Matches, WallschedVerb.Run),
        ("wallplan", WallplanVerb.Matches, WallplanVerb.Run),
        ("perim", PerimVerb.Matches, PerimVerb.Run),
        ("col-text", ColTextVerb.Matches, ColTextVerb.Run),
        ("sched-read", SchedReadVerb.Matches, SchedReadVerb.Run),
        ("sched-tokens", SchedTokensVerb.Matches, SchedTokensVerb.Run),
        ("dedupe-probe", DedupeProbeVerb.Matches, DedupeProbeVerb.Run),
        ("footings", FootingsVerb.Matches, FootingsVerb.Run),
        ("render", RenderVerb.Matches, RenderVerb.Run),
        ("elev-scan", ElevScanVerb.Matches, ElevScanVerb.Run),
        ("e2k-storeys", E2kStoreysVerb.Matches, E2kStoreysVerb.Run),
        ("wallconcrete", WallconcreteVerb.Matches, WallconcreteVerb.Run),
        ("single", SingleVerb.Matches, SingleVerb.Run),
        ("overlay", OverlayVerb.Matches, OverlayVerb.Run),
        ("rebar", RebarVerb.Matches, RebarVerb.Run),
    ];
}
