using Kor.Operations.EngineeringTools.PdfToSafe;
using UglyToad.PdfPig;

namespace Kor.Operations.EngineeringTools.Intake;

/// <summary>
/// The thirteen plan DXFs the intake is measured by: the same five stick files, the same pages, the
/// same scales, written to a folder named for the step, so <see cref="Dxf.DxfLayerCensus"/> can say
/// what the step moved. Regenerated by <c>takeoff intake-baseline</c>; until 2026-09-08 this list
/// lived in a shell loop and nowhere else.
/// </summary>
public static class IntakeBaseline
{
    /// <summary>A stick file, its plan pages and its scale denominator.</summary>
    public sealed record Job(string Number, int FirstPage, int LastPage, int Scale);

    /// <summary>The five local sets. File names are <c>{Number}.pdf</c> in the stick-file folder.</summary>
    public static readonly IReadOnlyList<Job> Jobs = new[]
    {
        new Job("31130-01", 11, 13, 96),
        new Job("31138-01", 9, 11, 96),
        new Job("31168-01", 11, 13, 96),
        new Job("31065-01", 14, 16, 100),
        new Job("31202-01", 17, 17, 96),
    };

    /// <summary>
    /// The DXF name a page is written to: <c>{job}-p{page:00}.dxf</c> for a multi-page job and
    /// <c>{job}.dxf</c> for a single page — the names the step folders have carried since step 1.
    /// </summary>
    public static string DxfName(Job job, int page)
        => job.LastPage > job.FirstPage ? $"{job.Number}-p{page:00}.dxf" : $"{job.Number}.dxf";

    /// <summary>
    /// Write the baseline: one DXF per plan page, compiled defaults for the rules, the drawing (not
    /// the markup) read, plan sheets only — exactly what <c>takeoff pdf-takeoff</c> does for each job.
    /// Returns the log lines; a missing stick file is a line, not an exception.
    /// </summary>
    public static IReadOnlyList<string> Write(string stickFilesDir, string outDir)
    {
        ArgumentNullException.ThrowIfNull(stickFilesDir);
        ArgumentNullException.ThrowIfNull(outDir);
        Directory.CreateDirectory(outDir);
        var (options, rulesSource) = PdfIntakeOptions.For(null);
        var log = new List<string> { $"baseline → {Path.GetFullPath(outDir)}   rules: {rulesSource}", "job        page  slabs  columns  walls  footings  axes  lines  file" };
        int written = 0;
        foreach (var job in Jobs)
        {
            string pdf = Path.Combine(stickFilesDir, job.Number + ".pdf");
            if (!File.Exists(pdf)) { log.Add($"{job.Number}  MISSING {pdf}"); continue; }
            using var doc = PdfDocument.Open(pdf);
            var facts = DocumentFacts.From(doc);
            var request = new IntakeRequest(job.Scale, options);
            for (int p = job.FirstPage; p <= job.LastPage; p++)
            {
                SheetRecord record;
                try { record = DrawingIntake.ReadSheet(doc, p, request, facts); }
                catch (Exception ex) { log.Add($"{job.Number}  {p,4}  FAILED {ex.GetType().Name}: {ex.Message}"); continue; }
                if (record.SheetType != "plan") { log.Add($"{job.Number}  {p,4}  {record.SheetType}: not a plan sheet; no DXF"); continue; }
                var geo = record.Geometry;
                if (geo.Slabs.Count + geo.Columns.Count + geo.Walls.Count + geo.Lines.Count == 0) { log.Add($"{job.Number}  {p,4}  empty"); continue; }
                string file = DxfName(job, p);
                DxfExporter.Export(geo, Path.Combine(outDir, file));
                written++;
                log.Add($"{job.Number}  {p,4}  {geo.Slabs.Count,5}  {geo.Columns.Count,7}  {geo.Walls.Count,5}  {geo.Footings.Count,8}  {geo.GridAxes.Count,4}  {geo.Lines.Count,5}  {file}");
            }
        }
        log.Add($"{written} DXF written.");
        return log;
    }
}
