# Installs remote control (the MeshCentral agent) on this machine, as SYSTEM, for one device group. Generated by
# Service/Mesh/MeshInstaller.cs, which fills in the server, group and pin placeholders; run through the NetworkOps agent or the network
# route like any fix. Downloads the group's installer from KOR-MESH01 (trusted by MeshTrust's rule: a certificate Windows
# validates, or the pinned self-signed one), installs under Program Files\KorOperations (admin-only; under the Webroot folder override), and deletes
# the installer. Already installed and running = nothing to do.
$ErrorActionPreference = 'Stop'
$existing = Get-CimInstance Win32_Service -Filter "Name='Mesh Agent'"
if ($existing -and $existing.State -eq 'Running') { 'already installed and running: {0}' -f [string]$existing.PathName; return }
$url = '{{URL}}/meshagents?id=4&meshid={{MESHID}}&installflags=0'
$stage = 'C:\Program Files\KorOperations\MeshStage'
$exe = Join-Path $stage 'KorMeshAgent64.exe'
New-Item -ItemType Directory -Force $stage | Out-Null
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
# Transport/MeshTrust.cs, the same rule: the pinned self-signed cert by exact hash, OR a cert Windows itself validates
# (trusted chain, right name, in date) AND issued by Let's Encrypt -- so another CA mis-issuing for this name is refused.
[Net.ServicePointManager]::ServerCertificateValidationCallback = {
    param($sender, $cert, $chain, $errors)
    $hash = [BitConverter]::ToString([Security.Cryptography.SHA256]::Create().ComputeHash($cert.GetRawCertData())) -replace '-', ''
    if ($hash -eq '{{CERTSHA256}}') { return $true }
    ([int]$errors -eq 0) -and ($cert.Issuer -like "*Let's Encrypt*")
}
try
{
    try { (New-Object Net.WebClient).DownloadFile($url, $exe) }
    finally { [Net.ServicePointManager]::ServerCertificateValidationCallback = $null }
    $r = Start-Process $exe -ArgumentList '-fullinstall', '--installPath="C:\Program Files\KorOperations\MeshAgent"' -Wait -PassThru -WindowStyle Hidden
    Start-Sleep -Seconds 5
}
finally
{
    # The installer never stays behind, whether the install worked or not; nor does the folder it came in.
    if ([IO.File]::Exists($exe)) { [IO.File]::Delete($exe) }
    if (-not [IO.Directory]::EnumerateFileSystemEntries($stage).GetEnumerator().MoveNext()) { [IO.Directory]::Delete($stage) }
}
$s = Get-CimInstance Win32_Service -Filter "Name='Mesh Agent'"
if (-not $s -or $s.State -ne 'Running') { throw ('installer exited {0}, but the Mesh Agent service is {1}' -f $r.ExitCode, $(if ($s) { [string]$s.State } else { 'not there' })) }
'installed; service {0} {1}; runs from {2}' -f [string]$s.State, [string]$s.StartMode, [string]$s.PathName
