<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kor.Operations.Core\Kor.Operations.Core.csproj" />
    <ProjectReference Include="..\Kor.Operations.Data\Kor.Operations.Data.csproj" />
    <ProjectReference Include="..\Kor.Operations.Rendering\Kor.Operations.Rendering.csproj" />
  </ItemGroup>

</Project>
