<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Kor.Opportunities.Core</AssemblyName>
    <NoWarn>$(NoWarn);SA0001</NoWarn>
    <StyleCopEnabled>false</StyleCopEnabled>
  </PropertyGroup>
</Project>
