USE [KorOpportunitiesDb];
SET QUOTED_IDENTIFIER ON;
SET XACT_ABORT ON;
BEGIN TRAN;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Aboriginal Coalition to End Homelessness', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=75846 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Acton Ostry Architects', Kind=N'Architect', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=76599 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'AgeCare', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=55033 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Alberni-Clayoquot Regional District', Kind=N'Buyer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=76364 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Alberta Cancer Foundation', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=53445 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Alberta Environment', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=53342 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Alberta Sustainable Resource Development', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=53349 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Alberta Wind Energy Corp.', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=53495 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Alexander Manor Holdings', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=55119 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Ann Davis Transition Society', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=76384 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Anthem Properties', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=76505 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Architecture49', Kind=N'Architect', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=74115 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Artists Urban Village', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=53442 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'ATCO Energy Solutions', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=53588 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'A Way Home Kamloops', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=76492 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Batistella Developments', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=53519 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'BC Children''s Hospital', Kind=N'Buyer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=70069 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'BC Ministry of Transportation', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=76617 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'BC Ministry of Transportation & Infrastructure', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=76226 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Bensen Manufacturing', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=70946 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Blue Sky Properties', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=76611 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Boss Developments', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=70617 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Brenhill Developments Ltd.', Kind=N'Buyer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=75870 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Calgary Municipal Land Corporation', Kind=N'Buyer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=74161 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Calgary Sports & Entertainment Corp', Kind=N'Buyer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=68785 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Calgary Urban Equities', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=53301 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Canadian Mental Health Association Kamloops', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=76356 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Canadian Mental Health Association Shuswap Revelstoke', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=76480 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'CapitalCare', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=76624 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Carscadden Stokes McDonald Architects Inc.', Kind=N'Architect', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=76544 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Catalyst Community Developments', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=72253 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Cenovus', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=68798 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Century Casinos', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=53431 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Chard Development Ltd.', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=75749 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Christenson Communities', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=53490 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'City of Duncan', Kind=N'Buyer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=69990 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'City of Medicine Hat', Kind=N'Buyer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=74346 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'CMHA Central Okanagan', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=76173 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'CMHA Kelowna', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=76172 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'CMHA Vernon', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=76491 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'CNRL', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=53475 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Community Land Trust', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=70072 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Community Land Trust Foundation of BC', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=70977 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Conseil scolaire francophone (SD 93)', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=75740 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Decidedly Jazz Danceworks', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=53533 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Devon NEC Corp.', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=53361 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'District of New Hazelton', Kind=N'Buyer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=69025 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Eagle Valley Senior Citizens Housing Society', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=76190 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'EIDOS Architecture', Kind=N'Architect', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=70672 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Embassy BOSA', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=53369 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'ENMAX Energy Corp.', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=53263 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Eyamethr Health Society', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=70026 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'First Capital Realty', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=53428 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Five Mile Holdings', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=55113 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Fort Hills Energy Corp.', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=53254 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Frame Properties', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=70649 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Francis Winspear Centre for Music', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=71196 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Fraser Health', Kind=N'Buyer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=69032 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Gibbs Gage Architects', Kind=N'Architect', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=71501 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Grant Connell Tennis', Kind=N'Buyer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=76606 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Greater Victoria Coalition to End Homelessness', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=70768 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Great Gulf', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=69259 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Grosvenor Canada', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=74354 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Groupe Germain Hospitalite', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=53267 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Haisla Nation', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=69389 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'HDR Architecture Associates Inc.', Kind=N'Architect', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=76527 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Hillwood Investment Properties', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=53266 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Hiyam ta Skwxwu7mesh Housing Society', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=75938 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Ho Goon Holdings Inc', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=70619 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Housing Okanagan Foundation', Kind=N'Buyer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=75851 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Imperial Oil', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=53393 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Iredale Architecture', Kind=N'Architect', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=76610 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'James KM Cheng Architects', Kind=N'Architect', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=69251 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Japan Canada Oil Sands Limited (JACOS)', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=53252 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'JTA Development Consultants', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=55107 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Kanaka Bar Indian Band', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=69372 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Katz Group of Companies', Kind=N'Buyer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=74338 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'K-Days', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=71192 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Keyera Corp.', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=53623 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Khowutzun Development LLP', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=75923 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Lilwat Business Group', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=69383 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Lower Similkameen Community Services Society', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=76478 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Lu''ma Native Housing Society', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=76476 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Luxuira Developments', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=70688 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'MCC Legacy Trust', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=71003 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'McLash Development Ltd', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=70651 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Metropia', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=53411 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Ministry of Technology Innovation and Citizens'' Services', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=69267 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Morphosis Architects', Kind=N'Architect', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=70957 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Mount Paul Apartments Kamloops 2024 Ltd.', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=75931 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'NAIT', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=68807 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Nchkay Development Corporation', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=70915 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'New Vista Society', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=76385 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Northern Biodiesel Limited Partnership', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=53373 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'North West Upgrading Inc.', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=53253 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'OHSU', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=68729 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Okanagan Metis & Aboriginal Housing Society', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=76167 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'OMA', Kind=N'Architect', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=68727 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Pacific National Exhibition (PNE)', Kind=N'Buyer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=75810 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'PAE', Kind=N'Architect', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=68718 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Pangman Development Corporation', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=71140 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Parkin Architects Ltd.', Kind=N'Architect', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=71476 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Parkin Architects Western Ltd.', Kind=N'Architect', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=76220 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Parkland Foundation', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=53538 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Peninsula Recreation Commission', Kind=N'Buyer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=70333 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Perkins&Will', Kind=N'Architect', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=69234 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Pickard Chilton', Kind=N'Architect', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=68737 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Plavetic', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=70589 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Port Moody Public Library', Kind=N'Buyer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=76388 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Primco Holdings', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=53649 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Providence Living', Kind=N'Buyer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=76391 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'RainCity Housing and Support Society', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=76580 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Reliance Properties', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=70935 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Revery Architecture', Kind=N'Architect', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=75935 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Royal BC Museum', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=69230 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Saanich Public Library', Kind=N'Buyer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=76037 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'SCDC', Kind=N'Buyer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=55098 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'School District 71 (Comox Valley)', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=69991 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Scwenwen Economic Development Corporation', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=75932 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Seattle Center', Kind=N'Buyer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=68714 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'SFU ChildCare Society', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=76390 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Shared Services BC', Kind=N'Buyer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=71056 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Silverbirch Hotels and Resorts', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=53448 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Skidegate Band Council', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=69385 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'SmartCentres REIT', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=70615 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Smoky Lake Foundation', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=53380 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Snuneymuxw First Nation Youth and Family Society', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=76369 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'South Skaha Housing Society', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=76479 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Stantec', Kind=N'Architect', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=75760 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Stantec Architecture', Kind=N'Architect', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=74103 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Strand Development', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=71042 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Summit Community Services Society', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=70067 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Taholah School District', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=70486 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Tennis Alberta', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=53456 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'The Bloom Group', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=55118 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'The Torgan Group', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=53511 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'TKA+D Architecture & Design', Kind=N'Architect', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=69583 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Tomo Spaces', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=71010 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Townline', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=70674 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Townline Housing', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=70676 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Turning Points Collaborative Society', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=76475 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'UBC', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=70886 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'UVic', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=75513 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'UW Medicine', Kind=N'Buyer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=68735 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Vancouver School Board', Kind=N'Buyer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=70883 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'W5 Arbutus Holdings', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=55114 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Wall Financial Group', Kind=N'Buyer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=54601 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Westbank Corp.', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=70911 AND RetiredAtUtc IS NULL;
UPDATE opportunities.CanonicalOrg SET DisplayName=N'Weytk Communities Inc', Kind=N'Developer', UpdatedAtUtc=sysdatetimeoffset() WHERE Id=70687 AND RetiredAtUtc IS NULL;
-- junk: null MPI canonical links + retire
UPDATE opportunities.MajorProjectsInventory SET ProponentCanonicalOrgId=NULL, UpdatedAtUtc=sysdatetimeoffset() WHERE ProponentCanonicalOrgId=76574;
UPDATE opportunities.MajorProjectsInventory SET ArchitectCanonicalOrgId=NULL, UpdatedAtUtc=sysdatetimeoffset() WHERE ArchitectCanonicalOrgId=76574;
UPDATE opportunities.CanonicalOrg SET RetiredAtUtc=sysdatetimeoffset(), UpdatedAtUtc=sysdatetimeoffset() WHERE Id=76574;
SELECT @@ROWCOUNT AS LastStmt;
COMMIT TRAN;
PRINT 'JV renames applied: 149';
