USE [KorOpportunitiesDb];
GO
SET QUOTED_IDENTIFIER ON;
GO
SET XACT_ABORT ON;
GO
/* Migration 246: thin-client deep enrichment. Generated from
   docs/enrichment-2026-06-20-thin-clients agent-A/B/C JSON.
   51 contacts / 30 org-meta updates / 30 orgs. */
DECLARE @Provider nvarchar(60) = N'ThinClientEnrich2026-06-20';
BEGIN TRAN;
DECLARE @meta TABLE (OrgId bigint, Website nvarchar(400), ProfileNote nvarchar(400));
INSERT INTO @meta (OrgId,Website,ProfileNote) VALUES
(20962, NULL, N'BC-based real estate developer and general contractor with offices in Vancouver (300-911 Homer St) and North Vancouver (25 Wallace Mews). Holds active BC Developer licence #45520 and GC licence #45122. No public-facing company website located.'),
(18992, N'https://reotech.ca', N'Coquitlam BC commercial interior construction specialist founded 1989; 51-200 employees. Delivers tenant improvements, construction management, and general contracting for office, healthcare, education, and hospitality clients across Metro Vancouver.'),
(20586, N'https://medcorp.ca', N'Surrey BC general contractor founded 2016 specializing in customized workspace buildouts for medical and dental professionals throughout the Lower Mainland. BBB A+ rating; six completed dental/medical clinic projects across Abbotsford, Coquitlam, Surrey, Maple Ridge, and Chilliwack.'),
(33440, N'https://www.oksfeldtdevelopments.com', N'North Vancouver boutique custom home builder and GC; family business tracing to 1953 Danish-immigrant founder Oksfeldt Molby. Holds BC General Contractor licence #53080. Focuses on select custom homes, renovations, and construction management in the Lower Mainland.'),
(10119, N'https://www.kdsconstruction.ca', N'Surrey BC general contractor and construction manager established 1984. Serves healthcare, institutional, commercial, food manufacturing, and light industrial sectors across Metro Vancouver and the Fraser Valley. 51-200 employees.'),
(55, N'https://www.vintop.ca', N'New Westminster BC developer and construction/marketing firm operating 30+ years; one-stop platform covering development management, construction, and sales. Notable for a BC Housing public-private partnership (66-unit PAL New West affordable rental, 2024) and the Ovation mid-rise in New Westminster.'),
(28005, N'https://www.cmpgroups.com', N'Vancouver-based vertically integrated general contractor and developer founded 2005; specializes in multi-family wood-frame apartments, townhomes, and commercial tenant improvement. Head office 408-2052 West 41st Ave, Vancouver. Combines construction management, development, and real estate finance.'),
(71980, N'https://www.metalbuildinggroup.ca', N'Surrey BC steel and metal building contractor (head office 303-15240 56th Ave, Surrey V3S 5K7) with 30+ years operating in Western Canada. Specializes in design-build pre-engineered metal buildings for industrial, commercial, agricultural, and recreational clients across BC and Alberta.'),
(36067, N'https://www.qualitech604.com', N'Family-owned Lower Mainland general contractor founded 2003; specializes in residential construction management, custom homes, and commercial tenant improvements. HPO-licensed; 2016 Georgie Awards finalist; 1,700+ units completed across Greater Vancouver.'),
(104, N'https://sakuradevelopments.com', N'Victoria BC real estate developer active since 1996; delivers multi-family condominiums, mixed-use, commercial, and custom single-family projects, managing land acquisition through sales. Distinct from the Vancouver-based Sakura Project Management entity.'),
(26285, N'https://www.boasconstruction.com', N'Port Coquitlam BC design-build contractor founded 2011; specializes in residential renovations, custom homes, commercial tenant improvements, and millwork. Small Korean-owned firm operating across Metro Vancouver. Distinct from Bosa Construction.'),
(20061, N'https://cressey.com', N'Established 1969 Vancouver real estate developer with a 57-year track record; delivers condominium, rental, and mixed-use projects across Metro Vancouver, Whistler, Alberta, and Washington State. Approximately 162 employees.'),
(11188, N'https://www.m3dm.ca/', N'Calgary-headquartered development management firm (est. 2016) with active BC offices in Vancouver (#330-34 W 7th Ave) and Victoria. Provides owner-rep, project management, cost management, and development management services for complex projects across Canada; BC work includes Senakw (1M sq ft, Vancouver, owner-rep for OPTrust).'),
(20176, N'https://www.pathgc.com/', N'Commercial general contractor based in Langley BC (8840 210th St, Langley BC V1M 2Y2), incorporated 2015. Specializes in commercial renovations including office, retail, restaurant, and base-building work across Metro Vancouver. A+ BBB rating. Provides design-build, design-assist, fixed-price, and construction management services.'),
(20607, N'https://www.seasonscontractingltd.com/', N'Commercial contractor based in Abbotsford BC (302A-33771 George Ferguson Way, V2S 2M5) specializing in dental and medical clinic construction and renovation across Metro Vancouver and Fraser Valley. 15+ years in business, 200+ completed projects. Turnkey service including interior design.'),
(148, NULL, N'BC-incorporated property holding company (incorporated 2007-09-25, LEI 549300R7S6DSL98VUR26) registered at 400-1245 West Broadway, Vancouver BC V6H 1G7. Owns the Delta Shoppers Mall site at 8037-8087 120 Street, North Delta (6-acre strip mall built 2004). Site approved Feb 2024 for 876-home mixed-use redevelopment by Value Property Group.'),
(210, N'https://www.alvairgroup.com/', N'Surrey BC residential developer (168-12830 96 Ave, Surrey BC V3V 0C2) with 25+ years building residential communities across BC. Develops single-family homes and multi-family residential projects in the Lower Mainland. Also operates as Alvair Development Ltd.'),
(37, N'http://armanihomes.ca/', N'Custom home builder and developer based in Port Moody BC (2 Greystone Place, Port Moody BC), serving the Tri-Cities area of Metro Vancouver. CHBA and HAVAN member. Builds custom single-family homes with personalized design via Choice Plans; partners with local sub-trades and land developers to create communities.'),
(176, N'https://axommconstruction.ca/', N'Vancouver-based general contractor and construction project manager with 20+ years of experience and 35+ delivered projects. Specializes in 5-storey mixed-use residential/commercial buildings, residential row houses, luxury residential, and tenant improvements across BC. Works with qualified trades and sub-contractors to reduce project costs.'),
(75124, N'https://bridgemarkdevelopment.com/', N'Vancouver-based real estate developer and consulting firm (#309-63 West 6th Ave, Vancouver BC V5Y 1K2; also cited at 998 Harbourside Dr, North Vancouver) with 35+ years of combined team experience and $3B+ in managed real estate. Active development pipeline in Surrey and Langley including high-rise towers; completed portfolio in Surrey, Coquitlam, Burnaby, and Vancouver. Also p'),
(35, N'https://corsadevelopments.com/', N'BC residential developer (604-537-7778) focused on building single-family homes, townhomes, and condos in the Lower Mainland. Tagline: ''Redefining the Urban Community.'' Online presence is limited and no leadership names are publicly listed. Distinct from Corsa Development Group (Post Falls, Idaho, USA).'),
(6947, N'https://enduroconstruction.ca', N'Vancouver-based full-service general contractor and construction management firm (office at #170-422 Richards St, Vancouver BC) operating across the Lower Mainland and Sea-to-Sky corridor. Specializes in commercial renovations, tenant improvements, institutional fit-outs and residential builds; clients include UBC and BC government. General inbox info@enduroconstruction.ca, ph '),
(213, NULL, N'BC private real estate development company registered as Gibbins Road Holdings Inc., active in the Cowichan Valley (Duncan / North Cowichan, Vancouver Island). Received unanimous council approval May 2024 for a 100-unit, 4-storey mixed-use rental building at 3096 Gibbins Rd, near Cowichan District Hospital.'),
(71895, N'https://gibraltar.ca', N'Gibraltar Holdings Ltd. (dba Gibraltar Construction) is a BC commercial general contractor founded 1993, HQ at 520 Sharpe St, New Westminster BC. Specializes in tenant improvements, dental/medical offices, financial institutions and commercial renovations across BC with 9,000+ completed projects. Ph (604) 874-9292.'),
(126, N'https://www.kyodaiproperties.com', N'Vancouver-based property management and real estate investment company; registered office Kyodai Holdings Ltd at 51 E Pender St, Vancouver BC. Manages a commercial and residential tenant portfolio; site references the Rennie organization. General inbox info@kyodaiproperties.com; no named staff published.'),
(118, N'https://www.moodyparkhomes.ca', N'Moody Park Homes Ltd is a Surrey-based BC home builder (est. 2013) focused on Lower Mainland residential development. The ''Edmonds J.V.'' suffix is a joint-venture designation; no separate public registration or JV partner surfaced. Phone 604-649-9793.'),
(206, N'https://www.plant-builders.com', N'BC-based general contractor / builder with a portfolio including a residential mixed-use development in Langford, BC. The ''plant-based'' branding likely refers to wood/sustainable construction. Website is live but most subpages return 404 as of June 2026; general inbox info@plant-builders.com. No named personnel found publicly.'),
(34554, N'https://www.prosperoussquare.com', N'Richmond, BC-based custom home builder and general contractor (est. 2014, Chinese-Canadian ownership). Serves residential and commercial renovation markets in greater Vancouver. Small firm (2-10 employees); BC contractor licences #53443 and #40455 now cancelled/inactive. General email prosperoussquare@gmail.com.'),
(120, NULL, N'BC-incorporated land developer; registered office Suite 509-1755 West Broadway, Vancouver. Beneficial owners are Karen Wai Har Woo, Edwin Ying Yuen Lee and Joanne Fay Kit Gunn. Active rezoning for a 26-storey, 208-unit purpose-built rental tower at 1668 West Broadway, Fairview (W.T. Leung Architects).'),
(5, N'https://willowtreehomes.ca', N'Surrey, BC-based land developer and homebuilder founded 2004 (Willow Tree Homes Ltd; office Unit 211-15292 Croydon Dr, Surrey BC). Builds eco-conscious residential communities (townhomes, condos, single-family) across Metro Vancouver, Fraser Valley and Chilliwack. General inbox info@willowtreehomes.ca.');
UPDATE o SET o.Website=COALESCE(o.Website,m.Website), o.Notes=COALESCE(o.Notes,m.ProfileNote), o.UpdatedAtUtc=sysdatetimeoffset() FROM opportunities.CanonicalOrg o JOIN @meta m ON m.OrgId=o.Id;
DECLARE @orgs TABLE (OrgId bigint);
INSERT INTO @orgs VALUES (5),(35),(37),(55),(104),(118),(120),(126),(148),(176),(206),(210),(213),(6947),(10119),(11188),(18992),(20061),(20176),(20586),(20607),(20962),(26285),(28005),(33440),(34554),(36067),(71895),(71980),(75124);
MERGE opportunities.CanonicalOrgEnrichment AS T USING (SELECT OrgId FROM @orgs) AS S ON T.CanonicalOrgId=S.OrgId AND T.ProviderName=@Provider WHEN NOT MATCHED THEN INSERT (CanonicalOrgId,ProviderName,Status,Attempts,CreatedAtUtc,UpdatedAtUtc) VALUES (S.OrgId,@Provider,N'Manual',0,sysdatetimeoffset(),sysdatetimeoffset());
DECLARE @people TABLE (OrgId bigint, PersonName nvarchar(200), Title nvarchar(200), Email nvarchar(200), Src nvarchar(20), Conf tinyint, Note nvarchar(400));
INSERT INTO @people (OrgId,PersonName,Title,Email,Src,Conf,Note) VALUES
(20962, N'Donald Cliburn', N'Person Responsible (BC Licence)', NULL, NULL, NULL, N'Listed as Person Responsible on BC developer and general contractor licences per BuildZoom licence records. No further public profile found.'),
(20962, N'Michael De Cotiis', N'Person Responsible (BC Licence)', NULL, NULL, NULL, N'Listed as Person Responsible on BC licences per BuildZoom. Note: a different Michael De Cotiis is President of Pinnacle International; BC corporate registry should be checked to confirm same vs distinct individual.'),
(18992, N'Al Dietrich', N'Principal (Founder)', NULL, NULL, NULL, N'Co-founder of Reotech Construction (est. 1989). Named on company About page as founding principal.'),
(18992, N'AJ Pratt', N'Principal', NULL, NULL, NULL, N'Named as principal on reotech.ca About page and LinkedIn company profile.'),
(18992, N'Ryan Turner', N'Principal', NULL, NULL, NULL, N'Named as principal on reotech.ca About page.'),
(18992, N'Ryan Thorpe', N'Principal', NULL, NULL, NULL, N'Named as principal on reotech.ca About page.'),
(18992, N'Reotech Reception (general inbox)', N'General Enquiries', N'reception@reotech.ca', N'website', 95, N'General reception inbox published on reotech.ca contact page (not a personal address). No direct principal emails publicly listed.'),
(20586, N'Gary Chohan', N'Project Coordinator', N'gary@medcorp.ca', N'website', 92, N'Listed on medcorp.ca home page as primary contact with mobile 604-385-2253 and office 604-897-9630. Only named individual on the site.'),
(33440, N'Ian Molby', N'Principal / Contractor', NULL, NULL, NULL, N'Listed as principal at Oksfeldt Developments per directory sources including opengovca.com. Second generation of the founding Molby family.'),
(33440, N'Jordan Molby', N'Contractor', NULL, NULL, NULL, N'LinkedIn profile confirms Jordan Molby as contractor at Oksfeldt Developments. Likely third generation of founding family. No email publicly available.'),
(10119, N'Kelly Shannon', N'President', N'info@kdsconstruction.ca', N'website', 30, N'Confirmed President and Secretary/Director per LinkedIn and directory sources. Email is the general company inbox only (not a personal address); no direct email found. Surrey-based.'),
(10119, N'Marvin Kale', N'Vice President', NULL, NULL, NULL, N'Confirmed VP at KDS Construction per LinkedIn. Credentials listed as PQS and GSC(F). Surrey-based.'),
(55, N'Luning Yu', N'President', N'info@vintop.ca', N'website', 30, N'Confirmed President via BC Gov news release (2024HOUS0056-000544) quoting Luning Yu on the PAL New West affordable housing delivery. Email is the general company inbox only (not a personal address).'),
(28005, N'Anita Dong', N'Co-Founder', NULL, NULL, NULL, N'Founding principal with background in urban planning, architecture, civil engineering, and construction management. Sourced from cmpgroups.com team page.'),
(28005, N'Darwin Lu', N'Co-Founder', NULL, NULL, NULL, N'Founding principal, structural engineer by training; former structural engineering professor in China and professional consulting engineer in Canada. Sourced from cmpgroups.com team page.'),
(71980, N'Jonathan Triance', N'President', NULL, NULL, NULL, N'President since 2019; joined the company in 2006. Oversees finance, sales, marketing, and project management. Sourced from metalbuildinggroup.ca/about-mbg/.'),
(71980, N'Trent Warkentin', N'Vice-President', NULL, NULL, NULL, N'30+ years with MBG in design, estimating, and project management. Leads the project management division. Sourced from metalbuildinggroup.ca/about-mbg/.'),
(71980, N'Lester Lam', N'Director of Business Development', NULL, NULL, NULL, N'Joined MBG in 2007. Leads BD; primary client-facing contact for new business. Sourced from metalbuildinggroup.ca/about-mbg/.'),
(71980, N'Jason Petty', N'Director of Finance', NULL, NULL, NULL, N'Background in accounting and construction finance; oversees corporate accounting and financial reporting. Sourced from metalbuildinggroup.ca/about-mbg/.'),
(36067, N'Serguei', N'Owner', NULL, NULL, NULL, N'Listed as owner/principal contact on BBB profile (surname garbled as ''Unkown'' in BBB registry, likely a data-entry error). No full last name or email confirmed from public sources.'),
(26285, N'Stuart Oh', N'Owner', NULL, NULL, NULL, N'Listed as owner on BBB registry and business licence records. No email confirmed from public sources.'),
(20061, N'N E Cressey', N'President', NULL, NULL, NULL, N'Listed as President on BBB registry. Norm Cressey is the founder; ''N E Cressey'' likely refers to Norm Cressey or a family member in the President role.'),
(20061, N'Scott Cressey', N'Manager', NULL, NULL, NULL, N'Listed as Manager on BBB registry; quoted on company website discussing building philosophy.'),
(20061, N'Hani Lammam', N'Executive Vice President', NULL, NULL, NULL, N'Confirmed EVP via LinkedIn, The Org, and multiple industry sources. Public-facing spokesperson on Vancouver real estate. Email domain is @cressey.com but full personal address not publicly confirmed.'),
(11188, N'Iain McCorkindale', N'Founder', NULL, NULL, NULL, N'Founder of M3DM; Calgary-based. Confirmed on company About page.'),
(11188, N'Nichola Sinclair-Foreman', N'Managing Director', NULL, NULL, NULL, N'Listed as Managing Director on M3DM About and LinkedIn pages.'),
(11188, N'Brandon Farrell', N'Director, BC Management & Operations', NULL, NULL, NULL, N'BC-specific director; confirmed on M3DM About page.'),
(11188, N'Ellie Sloper', N'Project Manager, Vancouver Office', NULL, NULL, NULL, N'Vancouver-office PM; confirmed on company LinkedIn profile.'),
(20176, N'Dennis Donovan', N'President / Director', N'dennis@pathgc.com', N'website', 90, N'Owner and operator of Path General Contractors; confirmed via BBB profile and LinkedIn (ca.linkedin.com/in/dennisdonovanpathgc). Phone: 604-595-1300.'),
(20607, N'Ameer Abu-Ulba', N'Owner / Red Seal Electrician', N'info@seasonscontractingltd.com', N'website', 70, N'Co-owner with background in electrical engineering from BCIT. Confirmed on company About page and federal corp directory (5285 Willet Rd, Abbotsford BC V3G 2E8). Shared general inbox email.'),
(20607, N'Vince Torrance', N'Owner / Red Seal Carpenter', NULL, NULL, NULL, N'Co-owner confirmed on company About page and ZoomInfo profile. ZoomInfo shows email exists but address is masked.'),
(210, N'Kunwar Bir Singh', N'Vice President', N'properties@alvairgroup.com', N'website', 60, N'VP confirmed on LinkedIn (ca.linkedin.com/in/kunwar-bir-singh), Greater Vancouver area. Email is the general company inbox, not personal. Phone: 778-320-0061.'),
(210, N'Justin Mandair', N'Vice President', NULL, NULL, NULL, N'VP confirmed on LinkedIn search results; also listed as founder of Mandair Consulting Inc. (concurrent role).'),
(37, N'Frank Ghorbani', N'Director', N'info@armanihomes.ca', N'website', 75, N'Director confirmed on company About page. Email is general inbox. Phone: (604) 551-7279.'),
(6947, N'Fred Roberge', N'Co-Founder / Principal', NULL, NULL, NULL, N'Co-founder and Principal at Enduro Construction Ltd. Confirmed via LinkedIn. ConstructConnect lists email domain @enduroconstruction.ca but full address is paywalled. No personal email found.'),
(6947, N'Joel Dumont', N'Co-Founder / Principal', NULL, NULL, NULL, N'Co-founder and Principal with 15+ years of construction management experience across residential and commercial projects. Confirmed via LinkedIn. Email domain @enduroconstruction.ca per ConstructConnect but full address paywalled.'),
(6947, N'Miguel Chango', N'Unknown', NULL, NULL, NULL, N'Listed as a third named contact on ConstructConnect alongside the two co-founders. Title and role not confirmed from any public source.'),
(71895, N'Paul Smeltzer', N'President / Director', NULL, NULL, NULL, N'President and Director of Gibraltar Holdings Ltd.; founding principal with 30+ years in BC commercial construction. Confirmed via LinkedIn and BBB profile.'),
(71895, N'David Smeltzer', N'Director', NULL, NULL, NULL, N'Director of Gibraltar Holdings Ltd., co-principal alongside Paul Smeltzer. Named in BBB profile as a principal.'),
(71895, N'Paul Massa', N'Director of Operations', NULL, NULL, NULL, N'Director of Operations at Gibraltar. Named in BBB profile as a principal; LinkedIn confirmed.'),
(71895, N'Jas Seble', N'General Manager', NULL, NULL, NULL, N'General Manager at Gibraltar Construction (Port Coquitlam BC). BCIT Construction Operations graduate. Confirmed via RocketReach and LinkedIn.'),
(118, N'Gurmeet Gill', N'President / Director', NULL, NULL, NULL, N'Listed as President and Director of Moody Park Homes Ltd per BBB profile. Also appears as a licensed BC real estate agent (REW). Phone on file 604-649-9793.'),
(118, N'Gursewak Gill', N'Director', NULL, NULL, NULL, N'Listed as Director of Moody Park Homes Ltd per BBB profile. No additional public profile found.'),
(118, N'Sadagar Gill', N'Director', NULL, NULL, NULL, N'Listed as Director of Moody Park Homes Ltd per BBB profile. No additional public profile found.'),
(34554, N'Lucas Li', N'Owner', NULL, NULL, NULL, N'Named as owner on BBB profile and confirmed by BuildZoom. Company general email is prosperoussquare@gmail.com (not a personal address). No direct email found.'),
(34554, N'Zhi Chao Li', N'Person Responsible (BC Housing Licensing)', NULL, NULL, NULL, N'Listed as the ''Person Responsible'' on BuildZoom BC contractor licence records for Prosperous Square Development Ltd. May be the same individual as Lucas Li or a separate officer.'),
(34554, N'Rose Zhang', N'Employee (title not confirmed)', NULL, NULL, NULL, N'Identified on LinkedIn company page as an employee. No title or further detail available publicly.'),
(120, N'Karen Wai Har Woo', N'Beneficial Owner', NULL, NULL, NULL, N'Named beneficial owner per Vancouver Council rezoning report (1668 West Broadway CD-1). No contact details publicly available.'),
(120, N'Edwin Ying Yuen Lee', N'Beneficial Owner', NULL, NULL, NULL, N'Named beneficial owner per Vancouver Council rezoning report. Multiple ''Edwin Lee'' realtors exist in Vancouver; do not conflate without confirmation.'),
(120, N'Joanne Fay Kit Gunn', N'Beneficial Owner', NULL, NULL, NULL, N'Named beneficial owner per Vancouver Council rezoning report. No contact details publicly available.'),
(5, N'Sunny Sangha', N'Principal / Developer', NULL, NULL, NULL, N'LinkedIn lists Willow Tree Homes as employer. Licensed BC realtor since 2005 (Century 21 Coastal Realty), Fraser Valley Medallion Club. His real estate firm shares the Willow Tree Homes phone number (604-356-5555), supporting principal-developer role. No email found.');
;WITH src AS (SELECT p.OrgId,p.PersonName,p.Title,p.Email,p.Src,p.Conf,p.Note,LOWER(LTRIM(RTRIM(p.PersonName))) AS Lowered,e.Id AS EnrId,CONVERT(CHAR(40),HASHBYTES('SHA1',CAST(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(LOWER(LTRIM(RTRIM(p.PersonName))),' ',''),'.',''),',',''),'''',''),'-',''),'&',''),'/',''),'(',''),')',''),'+','') AS VARCHAR(8000))),2) AS NK FROM @people p JOIN opportunities.CanonicalOrgEnrichment e ON e.CanonicalOrgId=p.OrgId AND e.ProviderName=@Provider)
MERGE opportunities.IntelPerson AS T USING src AS S ON T.NaturalKey=S.NK WHEN MATCHED THEN UPDATE SET LastSeenAtUtc=sysdatetimeoffset(),Corroborations=T.Corroborations+1,UpdatedAtUtc=sysdatetimeoffset(),Email=COALESCE(T.Email,S.Email),EmailSource=COALESCE(T.EmailSource,S.Src),EmailConfidence=COALESCE(T.EmailConfidence,S.Conf),Notes=COALESCE(T.Notes,S.Note)
WHEN NOT MATCHED THEN INSERT (SourceProviderName,SourceEnrichmentId,SourceConfidence,NaturalKey,FirstSeenAtUtc,LastSeenAtUtc,CreatedAtUtc,UpdatedAtUtc,DisplayName,NormalizedName,Corroborations,Email,EmailSource,EmailConfidence,EmailCheckedAtUtc,Notes) VALUES (@Provider,S.EnrId,N'Medium',S.NK,sysdatetimeoffset(),sysdatetimeoffset(),sysdatetimeoffset(),sysdatetimeoffset(),S.PersonName,S.Lowered,1,S.Email,S.Src,S.Conf,CASE WHEN S.Email IS NULL THEN NULL ELSE sysdatetimeoffset() END,S.Note);
;WITH aff AS (SELECT ip.Id AS PersonId,p.OrgId,p.Title,e.Id AS EnrId,CONVERT(CHAR(40),HASHBYTES('SHA1',CAST(CONCAT(CAST(ip.Id AS varchar(20)),'|',CAST(p.OrgId AS varchar(20)),'|',REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(LOWER(LTRIM(RTRIM(p.Title))),' ',''),'.',''),',',''),'''',''),'-',''),'&',''),'/',''),'(',''),')',''),'+','')) AS VARCHAR(8000))),2) AS NK FROM @people p JOIN opportunities.IntelPerson ip ON ip.NaturalKey=CONVERT(CHAR(40),HASHBYTES('SHA1',CAST(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(LOWER(LTRIM(RTRIM(p.PersonName))),' ',''),'.',''),',',''),'''',''),'-',''),'&',''),'/',''),'(',''),')',''),'+','') AS VARCHAR(8000))),2) JOIN opportunities.CanonicalOrgEnrichment e ON e.CanonicalOrgId=p.OrgId AND e.ProviderName=@Provider)
MERGE opportunities.IntelPersonAffiliation AS T USING aff AS S ON T.IntelPersonId=S.PersonId AND T.CanonicalOrgId=S.OrgId WHEN MATCHED THEN UPDATE SET Title=COALESCE(T.Title,S.Title),IsCurrent=1,LastSeenAtUtc=sysdatetimeoffset(),UpdatedAtUtc=sysdatetimeoffset()
WHEN NOT MATCHED THEN INSERT (SourceProviderName,SourceEnrichmentId,SourceConfidence,NaturalKey,FirstSeenAtUtc,LastSeenAtUtc,CreatedAtUtc,UpdatedAtUtc,IntelPersonId,CanonicalOrgId,Title,IsCurrent) VALUES (@Provider,S.EnrId,N'Medium',S.NK,sysdatetimeoffset(),sysdatetimeoffset(),sysdatetimeoffset(),sysdatetimeoffset(),S.PersonId,S.OrgId,S.Title,1);
PRINT 'Migration 246: thin-client enrichment (51 contacts / 30 org-meta).';
COMMIT TRAN;
GO

