USE [KorOpportunitiesDb];
GO
SET QUOTED_IDENTIFIER ON;
GO
SET XACT_ABORT ON;
GO
/* Migration 247: thin-client deep enrichment. Generated from
   docs/enrichment-2026-06-20-thin-clients agent-A/B/C JSON.
   76 contacts / 34 org-meta updates / 34 orgs. */
DECLARE @Provider nvarchar(60) = N'ThinClientEnrichW2-2026-06-20';
BEGIN TRAN;
DECLARE @meta TABLE (OrgId bigint, Website nvarchar(400), ProfileNote nvarchar(400));
INSERT INTO @meta (OrgId,Website,ProfileNote) VALUES
(19147, N'https://danesharchs.com', N'AIBC-registered architectural firm based in Vancouver, BC. Sole principal Alireza Danesh holds AIBC, AIA, NCARB, and MRAIC credentials with background in residential architecture and urban design. Website is under active reconstruction with no portfolio publicly accessible.'),
(26979, N'https://jywarchitecture.com', N'Vancouver BC architecture firm founded by Joe Y. Wai (1978), reincorporated 2016 under Principal Wan Qi. Specializes in social/affordable housing, residential care facilities, heritage restoration, and community/cultural projects exclusively in BC, with deep roots in Vancouver Chinatown and the Downtown Eastside.'),
(19095, N'https://radiant-city.com/', N'Vancouver BC small studio (est. 1994 as Division Zero Architecture) at #222-1118 Homer St. Focus on residential, mixed-use, and tenant improvement projects across Greater Vancouver and the Lower Mainland.'),
(20197, N'https://www.salikanarchitecture.ca/', N'Vancouver BC full-service studio founded 1988 at #923-409 Granville St. Specializes in commercial, institutional, recreational, and residential buildings; operates in BC and Alberta with past projects in the USA and Japan.'),
(23375, N'https://www.tkad.ca/', N'TKA+D is a Vancouver BC architecture and interior design practice (est. 2008) with 5 principals and approximately 40 staff. Works across commercial, industrial, institutional, and residential sectors in Greater Vancouver and Australia. Operating name TKA+D.'),
(23845, N'https://alabasterhomes.ca/', N'Boutique Vancouver BC residential developer (est. 2014) building single-family, multiplex, and rental projects across Vancouver neighbourhoods (Oakridge, Marpole, etc.). Emphasises design-driven construction and integrated post-occupancy homeowner services.'),
(23957, N'https://arborlea.ca', N'Surrey/Langley BC general contractor (est. 1986) specializing in tenant improvements for dental, medical, professional, and retail interiors across Greater Vancouver. Operates as a contractor/project manager, not a residential or commercial real estate developer.'),
(32155, N'https://www.bogner.ca', N'Bogner Kerrisdale Development Inc. is a project-specific subsidiary of Bogner Development Group Ltd. (Richmond BC, est. 1970s), a boutique residential developer building luxury low-to-mid-rise condos and townhomes across Vancouver west side and Surrey. The Kerrisdale entity corresponds to The Kirkland at 6168 East Blvd.'),
(22200, N'https://www.bucci.com', N'Bucci Garden Homes Ltd is a BC-registered project entity of Bucci Developments Ltd (Suite 202, 1669 West 3rd Ave, Vancouver BC), a third-generation family developer building mid-density residential condos and rentals across Western Canada. The entity is named for the 2550 Garden Drive project in East Vancouver.'),
(28435, N'https://catalystcommdev.org', N'Vancouver-based BC non-profit developer (309-877 East Hastings St, Vancouver BC V6A 3Y1) building purpose-built below-market rental housing across the Lower Mainland and Victoria. Partners with community organizations to unlock land value for affordable housing at 89-203 unit scale.'),
(38201, N'https://deecorp.ca/', N'Vancouver commercial real estate developer founded 1994 by Stanley Dee; $600M+ portfolio of retail, mixed-use, and hotel assets across BC. Currently advancing three 33-storey hotel towers totalling ~1,000 rooms in downtown Vancouver.'),
(20891, N'http://www.enticecreations.com', N'Burnaby, BC custom home builder and residential developer; HAVAN member since 2018. Office at 4556 Dawson Street, Burnaby BC V5C 4C1. Related entity Entice Building Materials Ltd (kitchen/bath supply) operates at the same address.'),
(21675, N'https://greenoakdevelopment.com', N'Vancouver BC luxury residential developer founded 2016; specializes in luxury estates, mixed-use, and multi-family projects on Vancouver''s West Side. Known for European/Italian design aesthetic with imported Italian finishes. Office at 4445 West 10th Ave, Vancouver BC V6R 2H8.'),
(20756, NULL, N'BC-registered developer and contractor incorporated 2013-05-04 in Delta, BC (BC Corp No. 0969245); formerly LHL Enterprises Ltd, renamed April 2016. Held City of Vancouver contractor licences 2016-2019; consistent with small infill or custom residential work in Greater Vancouver.'),
(51663, N'https://icegoc.com', N'ICE Group of Companies (legal: ICE Development Ltd), a Langley BC integrated design-build and development firm founded 2004. Operates across BC on multi-family residential, commercial, industrial, and municipal projects; ~10-50 employees. General contact: info@icegoc.com, 604-381-2202.'),
(22051, N'https://kutakdevelopment.com/', N'Vancouver BC real estate developer founded ~2015; provides full-scope services from acquisition through permitting, construction, and sales. Active in Metro Vancouver and Tri-Cities with multi-unit residential condo and rental projects.'),
(20518, NULL, N'Vancouver residential developer; formerly Matchpoint Development Ltd (name changed Feb 2019). Completed Chloe at 2096 W 47th Ave, Kerrisdale (46 strata + 11 retail units, 2024). Placed under receivership Feb 2025 (FTI Consulting appointed) due to liquidity crisis; company appears dormant.'),
(22259, N'https://livingspacehomes.com', N'Vancouver BC full-service residential developer and interior design firm founded 2013. Provides turn-key home building from site selection and permitting through construction management and European interior fit-out. Office: 120-1706 West 1st Ave, Vancouver BC V6J 0E4. General contact: info@livingspacehomes.com.'),
(24020, N'https://petersonbc.com', N'Development-arm entity of The Peterson Group, a major Vancouver family-owned developer founded 1959 by Peter Young. Headquartered at 1166 Alberni St, Vancouver. Portfolio of 23M+ sq ft spanning mixed-use residential, commercial, and hospitality across BC and North America.'),
(32397, NULL, N'BC developer incorporated as 1011180 B.C. Ltd., renamed Raichu Cambie Development Ltd. on 2018-07-09. Single-project vehicle for Winona on Cambie (7638 Cambie St, Vancouver), a 38-unit 6-storey condo completed ~2021 in the Cambie Corridor. Affiliated with Raichu Development Group, Surrey BC.'),
(21389, N'https://solarisproperties.ca/', N'Vancouver BC custom home builder and renovator operating since 1999; specializes in custom homes, full renovations, and house lifting in Metro Vancouver''s west side. Not a large-scale condo/strata developer. General contact: info@solarisproperties.ca.'),
(19717, N'https://www.terrablanka.com', N'Vancouver BC boutique developer founded 2013; specializes in luxury residential townhomes and multi-family projects on Vancouver''s West Side. Three completed/active projects in South Cambie and Oakridge. Office: 1281 W Georgia St, Vancouver BC. General contact: info@terrablanka.com.'),
(21798, N'https://tyko.ca', N'Vancouver-based fully integrated real estate developer and general contractor founded 2011, specializing in custom homes, laneway/coach homes, ADUs, and mixed-use commercial/residential development across the Lower Mainland.'),
(43596, N'https://www.bostonconstructioncorp.com', N'Surrey, BC general contractor founded 2005 (DBA Boston Builders Group), providing restoration, construction management, design-build, and new construction services across the Lower Mainland for residential, commercial, and municipal clients. Not related to any Massachusetts entity.'),
(49490, N'https://www.dawsonconstruction.ca/', N'Kamloops-based BC heavy civil contractor founded 1922; specializes in highway construction, paving, and aggregate supply across BC and Alberta. Part of the family-owned Dawson Group; one of four founding members of the BC Road Builders and Heavy Construction Association (1964).'),
(22060, N'https://gocancontracting.com', N'Richmond, BC-based general contractor providing commercial tenant improvements and residential construction across Greater Vancouver for 10+ years; specializes in retail TI, custom millwork, and design-build for shopping-centre and office clients.'),
(30335, N'https://jerichogeneralcontractors.com', N'Vancouver-based commercial general contractor (est. 2017) specializing in tenant improvements, building restoration, and design-build for offices, medical/dental clinics, churches, restaurants, and multifamily/strata buildings across Metro Vancouver.'),
(24124, N'https://www.lionsheadconstruction.com', N'Vancouver-based full-service commercial and residential general contractor founded 1996, specializing in dental and medical office construction and renovation across BC; 60+ professionals and sub-contractors with a niche in custom millwork and tenant improvement.'),
(12633, N'https://novacom.ca/', N'Surrey, BC-based construction manager and general contractor (DBA Novacom Building Partners) founded 1991. Specializes in tenant improvements, design-build, and construction management for commercial, institutional, and mixed-use projects across BC and Alberta.'),
(28554, N'https://weareperformance.ca', N'Richmond, BC general contractor (est. 2007, operating as Performance Builders Ltd.) specializing in multi-family market housing, social housing, and mixed-use design-build across Metro Vancouver; 65+ completed housing projects.'),
(19205, N'https://prismconstruction.ca', N'Delta, BC commercial and industrial general contractor founded 1998 by Amin Rawji. Specializes in design-build for self-storage, auto showrooms, warehouses, food processing, and film studio facilities; 600+ projects, 20M sq ft, $2B+ in construction value.'),
(19893, N'https://proformconstruction.ca', N'Small Burnaby, BC-incorporated general contractor (3 FTE) based at 3912 Spruce St, Burnaby; serves the Lower Mainland on residential and commercial design-build including condos, restaurants, and custom homes.'),
(20869, N'https://www.summitbrooke.com', N'Abbotsford, BC privately owned commercial general contractor founded 1998 (incorporated as Summit Brooke Development Corp). Specializes in multi-family townhomes, industrial tilt-up, corporate roll-outs, and tenant improvements throughout BC; COR certified with ~45-69 employees.'),
(22624, N'https://www.truemaple.com', N'Vancouver-based licensed general contractor and custom home builder incorporated December 2016, specializing in architect-designed custom homes, laneway homes, and residential renovations across 21 Lower Mainland municipalities. HAVAN member.');
UPDATE o SET o.Website=COALESCE(o.Website,m.Website), o.Notes=COALESCE(o.Notes,m.ProfileNote), o.UpdatedAtUtc=sysdatetimeoffset() FROM opportunities.CanonicalOrg o JOIN @meta m ON m.OrgId=o.Id;
DECLARE @orgs TABLE (OrgId bigint);
INSERT INTO @orgs VALUES (12633),(19095),(19147),(19205),(19717),(19893),(20197),(20518),(20756),(20869),(20891),(21389),(21675),(21798),(22051),(22060),(22200),(22259),(22624),(23375),(23845),(23957),(24020),(24124),(26979),(28435),(28554),(30335),(32155),(32397),(38201),(43596),(49490),(51663);
MERGE opportunities.CanonicalOrgEnrichment AS T USING (SELECT OrgId FROM @orgs) AS S ON T.CanonicalOrgId=S.OrgId AND T.ProviderName=@Provider WHEN NOT MATCHED THEN INSERT (CanonicalOrgId,ProviderName,Status,Attempts,CreatedAtUtc,UpdatedAtUtc) VALUES (S.OrgId,@Provider,N'Manual',0,sysdatetimeoffset(),sysdatetimeoffset());
DECLARE @people TABLE (OrgId bigint, PersonName nvarchar(200), Title nvarchar(200), Email nvarchar(200), Src nvarchar(20), Conf tinyint, Note nvarchar(400));
INSERT INTO @people (OrgId,PersonName,Title,Email,Src,Conf,Note) VALUES
(19147, N'Alireza Danesh', N'Principal Architect', N'info@danesharch.com', N'website', 70, N'Architect AIBC, AIA, NCARB, MRAIC based in Vancouver BC. Holds a Master of Architecture from UBC. Received 2nd place LafargeHolcim Sustainability Award (Next Generation category) for MArch thesis.'),
(26979, N'Wan Qi', N'Principal, Architect AIBC', N'wqi@jywarchitecture.com', N'website', 95, N'Acquired the firm in 2016 after 31 years with predecessor practice. B.Arch Southeast University (China), Architecte DPLG (Paris), registered AIBC. Leads heritage, care facility, and cultural/community work.'),
(26979, N'Peter Tang', N'Senior Technologist', N'ptang@jywarchitecture.com', N'website', 95, N'Senior technical staff at JYW Architecture Inc.'),
(26979, N'Guoqing Wang', N'Project Manager, Architect AIBC', N'gwang@jywarchitecture.com', N'website', 95, N'Project manager; AIBC-registered per ZoomInfo listing.'),
(26979, N'Marilyn Mortimer-Lamb', N'Administrator', N'mlamb@jywarchitecture.com', N'website', 95, N'Firm administrator.'),
(19095, N'Ron Bijok', N'Principal, Architect AIBC CP', N'office@radiant-city.com', N'website', 85, N'B.Sc (Arch.) and B.Arch. from McGill University. 10 years at Bobrow Fieldman Architects before founding firm in Vancouver in 1994. Formerly chaired AIBC Regulatory Coordination Working Group. 33+ years experience.'),
(19095, N'Ricardo Roffiel', N'Senior Associate, Architect AIBC', NULL, NULL, NULL, N'Handles complex projects and building envelope detailing. Listed on firm About Us page.'),
(19095, N'Jose Chan', N'Senior Associate, Architect AIBC CP CPHD', NULL, NULL, NULL, N'Handles Building Code services; Certified Passive House Designer. Listed on firm About Us page.'),
(19095, N'Samantha Rubio', N'Architectural Designer, B.Arch.', NULL, NULL, NULL, N'Leads residential and medium-sized projects including design and rendering. Listed on firm About Us page.'),
(20197, N'Robert Salikan', N'Principal Architect, MAIBC AAA MRAIC', N'info@salikanarchitecture.ca', N'website', 60, N'Founder of Salikan Architecture Inc. (est. 1988). Holds MAIBC, AAA, and MRAIC designations. Firm has operated in BC and Alberta with international project experience. General firm email; no personal email publicly listed.'),
(23375, N'Craig Taylor', N'President / Co-founder', NULL, NULL, NULL, N'MAIBC-designated architect; co-founded the firm in 2008. Listed as President on LinkedIn. General firm email is mail@tkad.ca (604 569-3499); no personal email publicly listed.'),
(23375, N'Donna Kurtz', N'Co-founder / Principal Interior Designer', NULL, NULL, NULL, N'BID designation; co-founded the firm in 2008 alongside Craig Taylor. No personal email publicly listed.'),
(23845, N'Herman Kwee', N'Partner', NULL, NULL, NULL, N'Listed as Partner on Alabaster Homes About page; identified as President in an Instagram reel. General contact is info@alabasterhomes.ca.'),
(23845, N'Nick Poon', N'Partner', NULL, NULL, NULL, N'Listed as Partner on Alabaster Homes About page. Also referenced as Executive Director in third-party sources.'),
(23845, N'Winston Chan', N'Director of Sales', N'winston@alabasterhomes.ca', N'news', 80, N'Director of Sales; email and direct line (604 767-3221) surfaced via LinkedIn public profile in search results. Primary sales contact for the firm.'),
(23957, N'Douglas Preston', N'President / Director', NULL, NULL, NULL, N'Listed as President and Director on BBB business profile. One of three Preston family principals (Douglas, Robert, Steve) running the firm.'),
(23957, N'Robert Preston', N'Vice President', NULL, NULL, NULL, N'Listed as VP on BBB business profile.'),
(23957, N'Steve Preston', N'Principal', NULL, NULL, NULL, N'Listed alongside Douglas and Robert Preston on BBB business profile. Specific title not stated.'),
(32155, N'Leon Bogner', N'President / Secretary', N'info@bogner.ca', N'website', 50, N'Founder and president of Bogner Development Group Ltd. Address: 302-4940 No. 3 Rd, Richmond BC V6X 3A5. General firm email only; no personal email publicly found.'),
(22200, N'Fred Bucci Jr.', N'Principal', NULL, NULL, NULL, N'Third-generation principal; quoted on company website as the public face of Bucci Developments Ltd. No direct email publicly listed.'),
(28435, N'Scott Dutchak', N'President', N'scott@catalystcommdev.org', N'news', 72, N'28+ years real estate experience; background includes TELUS real estate division and BCI. Holds MBA and professional urban planner credentials (CIP). Board member of Songhees Development Corporation.'),
(28435, N'Megan Pohanka', N'VP, Project Generation', NULL, NULL, NULL, N'Listed on Catalyst team page.'),
(28435, N'Robin Petri', N'VP, Development', NULL, NULL, NULL, N'Listed on Catalyst team page.'),
(28435, N'Sid Ahuja', N'VP, Finance', NULL, NULL, NULL, N'Listed on Catalyst team page.'),
(28435, N'Julie Taylorson', N'Board Chair', NULL, NULL, NULL, N'Board Chair per Catalyst team page.'),
(38201, N'Stanley Dee', N'President / Founder', NULL, NULL, NULL, N'Founded Deecorp in 1994; confirmed as President via LinkedIn. General company contact: info@deecorp.ca, 604-683-0002, Suite 201 - 388 West 8th Ave, Vancouver BC V5Y 3X2.'),
(38201, N'Karim Jiwa', N'General Counsel', NULL, NULL, NULL, N'Listed as General Counsel at Deecorp Properties Ltd on LinkedIn (ca.linkedin.com/in/karim-jiwa-062a9b8).'),
(20891, N'K.C. Cheng', N'Principal', N'info@enticecreations.com', N'news', 70, N'Named as company contact in HAVAN (Homebuilders Association Vancouver) member listing (joined May 2018). Houzz profile handle ''entice-kc'' corroborates initials. Full given name not publicly confirmed. Email is company general inbox from HAVAN directory.'),
(21675, N'Anna Asi', N'Executive Director', NULL, NULL, NULL, N'Confirmed via ZoomInfo, RocketReach, and LinkedIn profile as Executive Director at Green Oak Development Corp, Vancouver BC.'),
(21675, N'Michael Habibi', N'Vice President of Development', NULL, NULL, NULL, N'Listed as VP of Development on BBB filing (2016). LinkedIn now shows current role at Jadu Beauty; may have departed.'),
(51663, N'Sonny Sangha', N'President', NULL, NULL, NULL, N'President of ICE Group of Companies; confirmed via LinkedIn profile and Business Examiner article. No personal email found on public sources.'),
(22051, N'Patrik Kutak', N'Director', NULL, NULL, NULL, N'Listed as Principal Contact on BBB business profile. Company phone: (604) 417-4182.'),
(20518, N'Xiao Song Zheng', N'Founder / Principal (also known as Vicky Zheng)', NULL, NULL, NULL, N'Named in BC Supreme Court receivership documents (Case No. H-250150) as founder and personal guarantor on project financing. No email found in any public source.'),
(22259, N'Patti Lynch Yang', N'Interior Design / Project Management', NULL, NULL, NULL, N'Listed as employee on company LinkedIn profile in an interior design and project management role. No founder or principal name identified for the development entity.'),
(24020, N'Ben Yeung', N'Executive Chairman & CEO', NULL, NULL, NULL, N'Son of founder Peter Young; led Peterson since ~2000; DMD from UBC. NAIOP VCR Icon 2022 honoree.'),
(24020, N'Raymond Choy', N'President & CEO', NULL, NULL, NULL, N'CPA (Canada and Illinois); BBA from Simon Fraser University; 20+ years real estate experience.'),
(24020, N'Barrett Sprowson', N'Senior Vice President, Residential', NULL, NULL, NULL, N'Confirmed via The Org org chart for The Peterson Group.'),
(24020, N'Jane Young', N'Vice President, Corporate Relations', NULL, NULL, NULL, N'Confirmed via The Org org chart; likely family member of founder Peter Young.'),
(32397, N'Amandeep Rai', N'Principal', N'7600cambie@gmail.com', N'PatternInferred', 25, N'Listed as principal contact for Raichu Development Group Ltd. on BBB (Surrey BC). Gmail address attributed via D&B data aggregation only -- not confirmed on any official company source. Company phone: (604) 780-6132.'),
(21389, N'Richard Mullen', N'Founder / Owner', NULL, NULL, NULL, N'Founded company ~1999/2003; listed as owner on BBB and company About page. No personal email found.'),
(21389, N'Trevor Milne', N'Principal / Builder', NULL, NULL, NULL, N'Joined Solaris in 2010; listed as co-principal on company About page. No personal email found.'),
(19717, N'Ben Nour', N'Partner / Project Manager', N'b@terrablanka.com', N'PatternInferred', 35, N'Listed on LinkedIn as Partner/Project Manager at Terra Blanka. ZoomInfo confirms b***@terrablanka.com pattern. Single-initial format not verified on company website.'),
(19717, N'Kaveh Djahanshahi', N'Partner', N'k@terrablanka.com', N'PatternInferred', 30, N'Listed on LinkedIn as Partner at Terra Blanka; also Partner at Arkhaus Construction. ZoomInfo confirms k***@terrablanka.com pattern. Single-initial format not verified on company website.'),
(19717, N'Kian Zamani', N'Partner / Project Manager', NULL, NULL, NULL, N'Listed on Apollo.io as Project Manager/Partner at Terra Blanka. No email found.'),
(19717, N'Aidin Zadeh', N'', NULL, NULL, NULL, N'Listed as company contact in HAVAN (Homebuilders Association Vancouver) new member announcement. Title not confirmed from public sources.'),
(21798, N'Jack Nguyen', N'Co-Founder / Manager', NULL, NULL, NULL, N'Co-founder with 15+ years in construction; home renovator background. Listed as Manager on BBB profile. Brother-in-law of co-founder Ken. No personal email found publicly.'),
(43596, N'David (Devindej) Sidhu', N'President / Director', NULL, NULL, NULL, N'Principal owner and director per BBB profile; also director of related entity Boston Sheet Metal Ltd. ZoomInfo lists email domain as bostonconstructioncorp.com but full address not publicly confirmed.'),
(43596, N'Debbie Einarson', N'Project Administrator', NULL, NULL, NULL, N'Listed by ConstructConnect and SignalHire as Project Administrator at Boston Construction Corp, Surrey BC.'),
(43596, N'Shashi Anand', N'Construction Estimator', NULL, NULL, NULL, N'Listed by SignalHire as Construction Estimator at Boston Construction Corp, Surrey BC.'),
(43596, N'Rob Haggman', N'Site Superintendent', NULL, NULL, NULL, N'Listed by RocketReach and SignalHire as Site Superintendent; located in Ladysmith, BC.'),
(49490, N'Ian Dawson', N'Executive Chair, Dawson Group', NULL, NULL, NULL, N'Grandson of founder Fred Dawson (est. 1922). Director of Dawson Construction since 1986; Executive Chair across Dawson Group family of companies.'),
(49490, N'Lena Secord', N'President & CEO (interim), Dawson Group', NULL, NULL, NULL, N'Joined Dawson Group as Chief Human Resources Officer in October 2017; elevated to interim President & CEO. Oversees all Dawson Group entities including Dawson Construction Ltd.'),
(49490, N'Len Kazakoff', N'Vice President, Operations', NULL, NULL, NULL, N'Nearly 30 years at Dawson; based in Kamloops. Operational lead for both Dawson Construction Ltd and Dawson Civil throughout BC and Alberta.'),
(22060, N'Sunny Kwan', N'CEO', NULL, NULL, NULL, N'Named as CEO in the generalcontractors.org Vancouver retail contractor directory. Not confirmed on Gocan website directly; treat as single-source. General contact: info@gocangroup.com.'),
(24124, N'San Ashgar', N'General Contractor / Manager', NULL, NULL, NULL, N'Named on LinkedIn as affiliated with Lions Head Construction LTD; described on company About page as having 20+ years in construction management. No individual email found publicly.'),
(12633, N'Wes Drewlo', N'Founder', N'wes@novacom.com', N'website', 90, N'Founded Novacom in 1991; remains in mentorship/advisory role. Email listed directly on novacom.ca/story/ page. Note: email domain is novacom.com, not novacom.ca.'),
(12633, N'Brandon Drewlo', N'Principal & CEO', NULL, NULL, NULL, N'Son of founder Wes Drewlo. Joined as Project Manager in 2004; became President in 2015. Current title: Principal & CEO. Listed on company website.'),
(12633, N'Sharelle Dayco', N'Principal & Director of People and Culture', NULL, NULL, NULL, N'Listed as Principal on novacom.ca/story/ page.'),
(12633, N'Dan Poulsen', N'Director of Sales and Preconstruction', NULL, NULL, NULL, N'Listed on novacom.ca/story/ page. Key BD contact for preconstruction and sales.'),
(12633, N'Kevin Stuerle', N'Director of Finance', NULL, NULL, NULL, N'Listed on novacom.ca/story/ page.'),
(12633, N'Matthew Groot', N'Project Director', NULL, NULL, NULL, N'Listed on novacom.ca/story/ page.'),
(12633, N'Caleb Bender', N'Project Director', NULL, NULL, NULL, N'Listed on novacom.ca/story/ page.'),
(28554, N'Bernie Godler', N'President / Manager', NULL, NULL, NULL, N'Listed on LinkedIn and BBB as Manager/Principal Contact for Performance Construction Ltd., Richmond BC. Confirmed president per BCBusiness.'),
(28554, N'Daniel Kravcak', N'President, Construction Management', NULL, NULL, NULL, N'President listed on weareperformance.ca with 17+ years experience; certified project manager. Key operational contact.'),
(28554, N'Allan Deans', N'Business Development and Estimating', NULL, NULL, NULL, N'Listed on weareperformance.ca About page; 40+ years experience. Primary BD contact.'),
(28554, N'Olga Ilich', N'Principal', NULL, NULL, NULL, N'Former Executive VP at Progressive Construction (Richmond); confirmed partner/principal in Performance Construction Ltd per BCBusiness profile. Also Founder/President of Suncor Developments Ltd.'),
(28554, N'Milo Ilich', N'Principal', NULL, NULL, NULL, N'Confirmed co-principal of Performance Construction Ltd alongside Olga Ilich per BCBusiness and news sources.'),
(19205, N'Omar A. Rawji', N'President & Chief Executive Officer', NULL, NULL, NULL, N'Joined Prism in 2004; assumed CEO role 2022. Son of founder Amin Rawji. Led company to its $2B milestone (Jan 2025). LinkedIn: ca.linkedin.com/in/omar-a-rawji.'),
(19205, N'Amin Rawji', N'Founder', NULL, NULL, NULL, N'Quantity Surveyor (FRICS, PQS) trained in England; founded Prism 1998 after earlier career at Nova Construction. BBB lists him as President (legacy listing).'),
(19205, N'Reza Norozy', N'Chief Operating Officer', NULL, NULL, NULL, N'COO at Prism Construction Ltd. per business directory sources.'),
(19205, N'David Lee', N'Estimating Manager', NULL, NULL, NULL, N'Listed on BBB profile and business directories as Estimator/Estimating Manager.'),
(19205, N'Raj Marwaha', N'Operations Manager', NULL, NULL, NULL, N'Identified via business directory sources.'),
(19893, N'Sandeep Patel', N'President', NULL, NULL, NULL, N'Listed as President of Proform Construction Group Ltd on LinkedIn (ca.linkedin.com/in/sandeep-patel-874066148). No public email found on website, news, or registry.'),
(20869, N'Jonathon Brandt', N'Owner and President', N'jon.Brandt@summitbrooke.com', N'website', 95, N'Principal and founder. Email confirmed on Abbotsford Executives public business directory (abbotsfordexec.com/displayBusiness.asp?ID=14) and web search results. Phone: 604-850-1111.'),
(20869, N'Tamara Watt', N'Manager, Human Resources and Finance Supervisor', NULL, NULL, NULL, N'Listed as alternate company representative on BBB profile. Title sourced from ZoomInfo/Datanyze aggregators.'),
(22624, N'Jagdeep Phandal', N'President', N'jphandal@gmail.com', N'website', 95, N'President and primary contact. Email confirmed on truemaple.com contact page (personal Gmail; no corporate email domain). Phone: 604-603-1227. Address: Suite 451, 5525 West Blvd, Vancouver BC V6M 3W6. Also listed in federal registry as Jagdeep Singh Phandal.');
;WITH src AS (SELECT p.OrgId,p.PersonName,p.Title,p.Email,p.Src,p.Conf,p.Note,LOWER(LTRIM(RTRIM(p.PersonName))) AS Lowered,e.Id AS EnrId,CONVERT(CHAR(40),HASHBYTES('SHA1',CAST(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(LOWER(LTRIM(RTRIM(p.PersonName))),' ',''),'.',''),',',''),'''',''),'-',''),'&',''),'/',''),'(',''),')',''),'+','') AS VARCHAR(8000))),2) AS NK FROM @people p JOIN opportunities.CanonicalOrgEnrichment e ON e.CanonicalOrgId=p.OrgId AND e.ProviderName=@Provider)
MERGE opportunities.IntelPerson AS T USING src AS S ON T.NaturalKey=S.NK WHEN MATCHED THEN UPDATE SET LastSeenAtUtc=sysdatetimeoffset(),Corroborations=T.Corroborations+1,UpdatedAtUtc=sysdatetimeoffset(),Email=COALESCE(T.Email,S.Email),EmailSource=COALESCE(T.EmailSource,S.Src),EmailConfidence=COALESCE(T.EmailConfidence,S.Conf),Notes=COALESCE(T.Notes,S.Note)
WHEN NOT MATCHED THEN INSERT (SourceProviderName,SourceEnrichmentId,SourceConfidence,NaturalKey,FirstSeenAtUtc,LastSeenAtUtc,CreatedAtUtc,UpdatedAtUtc,DisplayName,NormalizedName,Corroborations,Email,EmailSource,EmailConfidence,EmailCheckedAtUtc,Notes) VALUES (@Provider,S.EnrId,N'Medium',S.NK,sysdatetimeoffset(),sysdatetimeoffset(),sysdatetimeoffset(),sysdatetimeoffset(),S.PersonName,S.Lowered,1,S.Email,S.Src,S.Conf,CASE WHEN S.Email IS NULL THEN NULL ELSE sysdatetimeoffset() END,S.Note);
;WITH aff AS (SELECT ip.Id AS PersonId,p.OrgId,p.Title,e.Id AS EnrId,CONVERT(CHAR(40),HASHBYTES('SHA1',CAST(CONCAT(CAST(ip.Id AS varchar(20)),'|',CAST(p.OrgId AS varchar(20)),'|',REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(LOWER(LTRIM(RTRIM(p.Title))),' ',''),'.',''),',',''),'''',''),'-',''),'&',''),'/',''),'(',''),')',''),'+','')) AS VARCHAR(8000))),2) AS NK FROM @people p JOIN opportunities.IntelPerson ip ON ip.NaturalKey=CONVERT(CHAR(40),HASHBYTES('SHA1',CAST(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(LOWER(LTRIM(RTRIM(p.PersonName))),' ',''),'.',''),',',''),'''',''),'-',''),'&',''),'/',''),'(',''),')',''),'+','') AS VARCHAR(8000))),2) JOIN opportunities.CanonicalOrgEnrichment e ON e.CanonicalOrgId=p.OrgId AND e.ProviderName=@Provider)
MERGE opportunities.IntelPersonAffiliation AS T USING aff AS S ON T.IntelPersonId=S.PersonId AND T.CanonicalOrgId=S.OrgId WHEN MATCHED THEN UPDATE SET Title=COALESCE(T.Title,S.Title),IsCurrent=1,LastSeenAtUtc=sysdatetimeoffset(),UpdatedAtUtc=sysdatetimeoffset()
WHEN NOT MATCHED THEN INSERT (SourceProviderName,SourceEnrichmentId,SourceConfidence,NaturalKey,FirstSeenAtUtc,LastSeenAtUtc,CreatedAtUtc,UpdatedAtUtc,IntelPersonId,CanonicalOrgId,Title,IsCurrent) VALUES (@Provider,S.EnrId,N'Medium',S.NK,sysdatetimeoffset(),sysdatetimeoffset(),sysdatetimeoffset(),sysdatetimeoffset(),S.PersonId,S.OrgId,S.Title,1);
PRINT 'Migration 247: thin-client enrichment (76 contacts / 34 org-meta).';
COMMIT TRAN;
GO

