#nullable enable
namespace Kor.Operations.NetworkOps.Core.Learning;

/// <param name="Meaning">What the finding says, in one or two plain sentences.</param>
/// <param name="Fixes">Known fixes, most likely first -- each learned on this fleet where it says so.</param>
/// <param name="IfIgnored">What happens if nobody acts.</param>
public sealed record KnowledgeEntry(string Family, string Meaning, IReadOnlyList<string> Causes, IReadOnlyList<string> Fixes, string IfIgnored);

// What each kind of finding means and what has fixed it, written from KOR's own 2026 diagnoses rather
// than generic advice. Learned fixes (FixLearning) are shown beside these as the fleet accumulates
// evidence. A test fails if any rule can raise a family that has no entry here.
public static class Knowledge
{
    public static KnowledgeEntry? For(string ruleKey) => Entries.TryGetValue(FixLearning.FamilyOf(ruleKey), out var e) ? e : null;

    public static IReadOnlyCollection<string> Families => Entries.Keys;

    private static readonly Dictionary<string, KnowledgeEntry> Entries = new[]
    {
        E("wmi-broken", "Windows Management Instrumentation is not answering, so most health reads fail and the machine is partly blind to monitoring.",
            ["A corrupted WMI repository (KOR-213, Sep 2026)"],
            ["Run `winmgmt /verifyrepository`; if inconsistent, `winmgmt /salvagerepository`", "Restart the Winmgmt service", "Last resort: `winmgmt /resetrepository` and reboot"],
            "Inventory, disk health and most checks stay blind on this PC; faults will not be seen."),
        E("disk-missing", "A drive Windows used to see is no longer present, and any drive letter it had now points at nothing.",
            ["The drive has failed (KOR-206-N's Samsung 870 EVO, Sep 2026, after bad blocks and resets)", "A loose SATA data or power cable"],
            ["Reseat the SATA data and power cables", "If it returns: copy its data off at once, then replace it", "If not: data recovery from the drive in a USB adapter"],
            "Whatever was only on that drive is lost."),
        E("disk-failing", "A drive is reporting bad blocks, file-system corruption or repeated controller resets -- the classic run-up to failure.",
            ["Failing flash or platters", "A marginal cable or port (resets without bad blocks)"],
            ["Copy its data to a safe place now", "Replace the drive", "If only resets: try another cable and SATA port first"],
            "The drive can vanish without warning, as 206-N's D: did three weeks after its first bad blocks."),
        E("gpu-hangs", "The graphics driver keeps timing out and resetting (video engine timeout, 0x141). Users see freezes and black flashes.",
            ["A card that is failing or dropping off the bus (104N shows no NVIDIA card at all)", "A card not seated properly", "An old driver on an old Quadro",
             "NOT a fleet-wide model problem: the Sep 2026 'P340 9 of 10' figure counted years-old reports still queued for sending. Dated by report creation (probe v8, 2026-10-01), 1 of 7 flagged PCs (KOR-104N) had real resets in 14 d"],
            ["Install the current NVIDIA workstation driver for that card (clean install)", "Reseat the card and its power connector", "Replace an old Quadro that still hangs on a current driver"],
            "Constant freezes in Revit and CAD; eventually the card drops out entirely."),
        E("unexpected-shutdowns", "The PC is losing power or crashing hard without a clean shutdown.",
            ["A blue-screen crash", "Power loss or a failing PSU", "Overheating"],
            ["Look up the bug-check in the System log around the time", "Check the PSU and power cable; move it to a UPS outlet"],
            "Open work is lost each time, and a crash can corrupt files."),
        E("hardware-errors", "The processor, memory or PCIe bus is reporting hardware errors (WHEA warnings or errors; informational WHEA notices are not counted).",
            ["A failing component", "A device misbehaving on the PCIe bus (often a disk or GPU)"],
            ["Read the WHEA events to see which component", "Update the BIOS", "Replace the named component"],
            "Hardware errors precede crashes and data corruption."),
        E("memory-layout", "The RAM is installed so that part or all of it runs slower than it could: channels holding different amounts (the surplus runs single-channel), or modules running well below their rated speed.",
            ["An odd number of modules, or mismatched sizes across channels (206-N: 32 GB on one channel, 64 GB on the other)",
             "Two modules on one DDR5 channel, which lowers the speed of the whole set (206-N: 4800 rated, 3600 actual)",
             "XMP/EXPO or memory speed turned down in the BIOS"],
            ["Balance the channels: add a matching module (206-N: a 4th 32 GB = 128 GB, balanced) or remove one (64 GB, one per channel, full rated speed)",
             "Match the part numbers when adding", "Check the BIOS memory speed setting"],
            "Nothing breaks: large models, analysis runs and big drawings are slower than the hardware allows."),
        E("crash-loop", "An application keeps crashing.",
            ["opushutil.exe: Office on machines with the Access Database Engine (13 PCs, 2026)", "Revit/Bluebeam: version-specific faults (207, 308)", "A corrupt profile or add-in"],
            ["Update the application", "Repair Office for opushutil", "Reset the app's user profile/preferences"],
            "The user loses work and time with every crash."),
        E("outlook-index", "Windows Search cannot index a mailbox file, so Outlook search misses mail.",
            ["A damaged mailbox store -- a rebuild did NOT fix it on 206-N (Jul and Sep 2026)"],
            ["Recreate the Outlook profile (new OST) rather than rebuilding the index again"],
            "Searches silently miss results."),
        E("office-access-engine-stale", "The Access Database Engine left 2020-era Office DLLs that hijack Click-to-Run Office.",
            ["Access Database Engine 2016 redistributable, unpatched"],
            ["Update the redistributable (KB5002623 or later) -- never delete the folder, Excel/Access data access depends on it", "Turn on Microsoft Update so Office MSI patches arrive"],
            "Office components keep crashing daily."),
        E("low-disk", "A drive is nearly full.",
            ["Growing project caches, temp files, old installers, a large mailbox file"],
            ["Clear temp and old installers", "Move project data to the server", "Add or enlarge the drive"],
            "Saves and syncs to that drive start failing when it fills; if it is C:, Windows updates and most applications fail too."),
        E("reboot-overdue", "Updates are installed but waiting on a restart, and the PC has been up for days.",
            ["The PC is never restarted"], ["Restart it"],
            "Security fixes are not active until the restart."),
        E("not-patched", "No Windows update has installed in over a month.",
            ["Updates failing", "Update scheduling off (Ninja's NoAutoUpdate policy with nothing driving updates)"],
            ["Check Windows Update history for failures", "Run the update manually"],
            "Known security holes stay open."),
        E("microsoft-update-off", "Microsoft Update is not registered, so Office MSI patches (Access Database Engine) are never offered.",
            ["Only Windows Update was ever enabled"], ["Opt in to Microsoft Update (done fleet-wide 28 Sep 2026)"],
            "Office components stay unpatched."),
        E("fan-profile-loud", "The BIOS fan profile holds the fans high even when the PC is idle and cool.",
            ["Lenovo 'Performance' or 'Best Performance' cooling mode (KOR-305, 206-N)"],
            ["Fix… > Set the fans to the quiet profile: 'Best Experience' on a P340, 'Balance mode' on a P350/P360 (applies after a restart)", "If still loud when idle and cool: a dusty or failing fan (305's rear exhaust fan)"],
            "Noise complaints; no thermal risk."),
        E("disk-unmounted", "A data drive is still connected, but Windows no longer shows its data: the partition has lost its volume and its letter.",
            ["The drive is failing: bad blocks and controller resets came first on KOR-208-N (2026-10-02)", "A loose or failing SATA cable or port", "The partition table or file system was damaged"],
            ["Do NOT format it or run CHKDSK on it", "Copy the data off with a recovery tool (or send the drive to recovery) first", "Then replace the drive and restore the data to a backed-up place"],
            "The data on it may be lost for good, and every write makes recovery harder."),
        E("bios-behind", "Lenovo has a newer BIOS for this PC than the one it runs (read from Lenovo's own catalog, the same answer Lenovo's updater gives).",
            ["BIOS updates are never installed automatically; on Lenovo they also carry the Intel ME firmware (11 of 22 AMT PCs behind, Oct 2026)"],
            ["Fix… > Check the BIOS update (verifies, flashes nothing)", "Fix… > Update the BIOS: restarts in 5 minutes with a warning; pick a time nobody is on it"],
            "Firmware security fixes and Intel ME/AMT fixes go uninstalled."),
        E("unbacked-data", "Real data sits on a drive that no backup covers.",
            ["Work kept on a second local drive (13 months of 206-N's work lived only on D:)"],
            ["Move the data into OneDrive or onto the server", "Turn on OneDrive known-folder backup"],
            "If the drive fails, the data is gone -- as it nearly was on 206-N."),
        E("remote-tools-stale", "Older generations of remote-access agents are still installed and running as SYSTEM.",
            ["MSP agents from 2022 and 2023 never uninstalled"], ["Uninstall the older ScreenConnect instances"],
            "Old remote-access software is a known target."),
        E("newforma-residue", "Newforma leftovers remain after its removal.",
            ["Uninstall missed the PDF component and per-user caches"], ["Uninstall Newforma PDF; delete AppData\\Local\\Newforma"],
            "Webroot keeps flagging the leftover DLLs."),
        E("probe-incomplete", "Part of the health check could not read this PC, so its picture is incomplete.",
            ["A component the probe reads is missing or broken on this machine"], ["Look at the named block; fix the component"],
            "Faults in the unread part go unseen."),
        E("device-silent", "The PC has not answered for days.",
            ["Switched off, disconnected, off the VPN, or retired"], ["Confirm with its user; retire it in NetworkOps if it is gone"],
            "Nothing is known about it -- silence is itself the finding."),
        E("disk-filling", "At the current rate a drive will run out of space soon.",
            ["Steady growth of caches, projects or mail"], ["Clear space or move data before the date", "Find what is growing"],
            "Applications and updates fail on the day it fills."),
        E("mailbox-near-limit", "An Outlook mailbox file is approaching Outlook's 50 GB ceiling.",
            ["A large mailbox cached in full"], ["Archive old mail", "Limit the cached period (Cached Exchange Mode slider)", "Raise the OST limit by policy"],
            "At 50 GB Outlook stops syncing and mail stops arriving in the client."),
        E("disk-wearing", "An SSD is using up its rated write endurance.",
            ["Heavy writes over years"], ["Plan a replacement", "Replace above 90%"],
            "A worn-out SSD can go read-only or fail."),
        E("disk-errors", "A drive has started logging read or write errors.",
            ["Failing media", "A bad cable (for SATA)"], ["Copy the data off", "Replace the drive"],
            "Errors grow into failure; unrecoverable reads mean data is already being lost."),
        E("disk-aging", "An old spinning hard drive is still in service.",
            ["Original drive from a long-lived PC"], ["Move its data off and replace it with an SSD"],
            "Hard drives fail more often past about five years."),
        E("gpu-hangs-rising", "Graphics hangs are increasing week on week.", ["See gpu-hangs"], ["See gpu-hangs"], "Heading toward constant freezes."),
        E("app-hangs-rising", "Programs are freezing more often than last week.", ["Memory pressure, a failing disk, an add-in"], ["Check memory and disk findings on this PC"], "Freezes turn into crashes."),
        E("memory-pressure-rising", "Windows is running low on memory more often.", ["Too many heavy apps open at once", "A memory leak"], ["Close unused apps; add RAM; enlarge the page file"], "Apps start failing and crashing."),
        E("disk-resets-rising", "Drive controller resets are increasing.", ["See disk-failing"], ["See disk-failing"], "A drive about to drop out."),
        E("hardware-errors-rising", "Hardware errors are increasing.", ["See hardware-errors"], ["See hardware-errors"], "Crashes and corruption."),
        E("crashes-rising", "An application is crashing more often than last week.", ["A recent update or add-in"], ["See crash-loop"], "More lost work."),
        E("boot-slowing", "The PC takes much longer to start than it used to.", ["A failing disk", "Startup programs", "Group Policy waiting on a dead share"], ["Check disk health; review startup items; check GPO drive maps"], "Slow starts often precede disk trouble."),
        E("battery-worn", "The laptop battery holds much less charge than new.", ["Age and cycles"], ["Replace the battery"], "Short runtime; a worn battery can swell."),
        E("os-unsupported", "The PC runs Windows 10, which stopped receiving security updates on 14 Oct 2025.", ["Not yet upgraded, or hardware that cannot run Windows 11"], ["Upgrade to Windows 11, or replace the PC"], "Every new Windows vulnerability stays open on it."),
        E("not-restarted", "The PC has not been restarted in over a month.", ["Left on and locked"], ["Restart it"], "Pending fixes never apply; small leaks accumulate."),

        // ---- the rack (Core/Rack). Written from what this rack has actually done.
        E("rack.unreachable", "NetworkOps could not read this device, so nothing about its health is known right now.",
            ["The device is off, rebooting or hung", "A network or switch fault between APP01 and it", "Its read-only credential or pinned key changed"],
            ["Check the device is up (ping it, open its web page)", "Read the evidence: a refused key or certificate means it was replaced or re-keyed; re-pin it only once you know why"],
            "Its other findings stay as last seen; a new fault on it goes unseen until it answers again."),
        E("esxi.clock", "The host's clock is wrong. VMs take their time from it at boot and at snapshots, and Windows sign-in (Kerberos) fails past 5 minutes of skew.",
            ["PTP turned on instead of NTP with no PTP master on the network (host .10, 35 min slow, Sep 2026)", "NTP off or its firewall rule closed"],
            ["esxcli system ptp set -e false; esxcli system ntp set -e true; set ntpd to start with the host", "Set the time once (esxcli system time set) -- NTP will not correct a gap this large by itself"],
            "Snapshots and reboots jolt the VMs' clocks; sign-ins and backups start failing."),
        E("esxi.ntp", "Time sync (NTP) is not running or will not start with the host.", ["Disabled in the host's time settings", "Replaced by PTP"],
            ["Enable NTP with start policy 'on' (Host > Manage > System > Time & date)"], "The clock drifts until something breaks (see esxi.clock)."),
        E("esxi.ptp", "The host uses PTP for time, which needs a PTP master on the network. KOR has none, so the clock free-runs.",
            ["PTP selected in the host's time settings (host .10, Sep 2026)"], ["Switch the host to NTP (see esxi.clock)"], "The clock drifts: host .10 reached 35 minutes slow."),
        E("esxi.maintenance", "The host is in maintenance mode: no VM on it can be powered on.",
            ["Left in maintenance mode after work", "A clean scripted shutdown: ESXi comes back up STILL in maintenance mode (25 Sep 2026)"],
            ["vim-cmd hostsvc/maintenance_mode_exit (or Exit maintenance mode in the host client)"], "After a power cut, the VMs on it stay off."),
        E("esxi.sensors-blind", "The host reports no hardware sensors, so a failed power supply, fan or temperature problem is invisible.",
            ["The CIM service (wbem) switched off (host .16, Sep 2026)"], ["esxcli system wbem set -e true"],
            "A dead PSU goes unseen: one did on host .10 for 173 days."),
        E("esxi.sensor", "A hardware sensor on the host is out of range or failed (power supply, fan, temperature, memory, storage).",
            ["A failed or unplugged power supply (host .10's PSU1 was AC-lost 173 days)", "A failing fan", "A hot room"],
            ["Read which sensor; for a PSU, check its cord and that it lands on a live UPS outlet", "Replace the failed part"],
            "The host runs on its remaining redundancy until that fails too."),
        E("esxi.stale-mount", "A datastore Veeam mounted for an instant recovery is left behind, inaccessible.", ["An old Veeam instant recovery or SureBackup session"],
            ["Unmount it (Host > Storage) once no restore is running"], "Nothing; it is clutter that can hide a real lost datastore."),
        E("esxi.datastore-lost", "A datastore the host uses is not accessible: VMs on it cannot run.",
            ["The UC3200 SAN or its iSCSI path is down", "A network fault on the storage VLAN"], ["Check the SAN, then rescan storage on the host"], "Every VM on it is down."),
        E("esxi.datastore-full", "A datastore is running out of space.", ["VM growth", "Forgotten snapshots"], ["Delete old snapshots; move or grow VMs"],
            "A full datastore pauses every VM on it."),
        E("esxi.vm-off", "A production VM is not running.", ["Shut down or crashed", "Did not start after a host reboot"], ["Power it on; find out why it stopped"],
            "Whatever it serves (files, sign-in, apps, backups) is down."),
        E("esxi.vm-tools", "VMware Tools is not running in a production VM.", ["Tools stopped or out of date"], ["Restart or update VMware Tools in the guest"],
            "The UPS shutdown chain cannot shut it down cleanly -- it would be powered off hard."),
        E("esxi.memory", "The host's RAM is nearly all in use.", ["Too many or too large VMs"], ["Move a VM to the other host; add RAM"], "VMs start swapping and slow down."),

        E("syno.system", "The Synology reports a system failure.", ["A hardware fault"], ["Open DSM > Info Center; contact Synology"], "The box may stop serving storage."),
        E("syno.power", "A power supply on the Synology has failed or lost power.",
            ["A backed-out cord or unlatched module (the UC3200's PSU2 dropped out repeatedly 2023-2026)", "A failed PSU"],
            ["Reseat the PSU and its cord (safe live on a redundant box)", "Replace it if it keeps dropping"], "The box runs on one supply; the next failure takes it down."),
        E("syno.fan", "A system fan on the Synology has failed.", ["A worn fan"], ["Replace the fan"], "The box overheats and throttles or shuts down."),
        E("syno.cpu-fan", "The Synology's CPU fan has failed.", ["A worn fan"], ["Replace the fan"], "Overheating."),
        E("syno.temp", "The Synology is running hot.", ["A hot rack", "A failed fan or blocked vents"], ["Check the fans and airflow"], "Disks age faster; the box shuts down to protect itself."),
        E("syno.update", "A DSM update is available for this box.", ["A new release"],
            ["Install it in a maintenance window with the VMs down (the SAN's update fails storage over between controllers)"], "Known issues and security fixes stay unapplied."),
        E("syno.disk", "A disk in the Synology is failing or has failed.", ["Age, bad sectors"], ["Replace the disk (hot-swap) and let the RAID rebuild"],
            "The RAID loses its redundancy; one more failure loses the volume."),
        E("syno.raid", "A RAID group or volume is degraded, rebuilding or crashed.", ["A failed disk", "A rebuild in progress"],
            ["Replace the failed disk; leave the box alone while it rebuilds"], "A degraded array is one disk away from data loss."),
        E("syno.volume-full", "A volume is filling up.", ["Data growth", "Snapshots"], ["Free space or expand the pool"], "Writes fail when it is full."),

        E("veeam.failed", "A backup job's last run FAILED: the machines in it were not backed up.",
            ["VSS could not snapshot the guest -- heavy writes during the snapshot, stuck VSS writers (Kor-FS01, 30 Sep 2026)", "A repository full or offline"],
            ["Read the job's session log in Veeam", "For VSS: on the guest run `vssadmin list writers`; restart the failed writers' services or reboot the guest, then retry the job"],
            "Each day it fails is a day of changes with no backup."),
        E("veeam.warning", "A backup job finished with warnings: the backup exists but something in it was skipped or degraded.",
            ["Guest file indexing without credentials (KOR-UNIFI01, fixed 29 Sep 2026)", "A VM with a problem on its disks or tools"],
            ["Read the warning in the job's session log"], "Warnings usually precede failures."),
        E("veeam.stale", "A backup job has not run when it should have. This is the SILENT failure: nothing errors, the backups just stop.",
            ["The job was disabled or its schedule removed (8 days of silence, 2026)", "The Veeam service or BK01 is down"],
            ["Check the job is enabled and scheduled; check BK01 is running"], "No backups at all, and nobody told."),
        E("veeam.disabled", "A backup job is disabled.", ["Disabled for maintenance and not re-enabled"], ["Re-enable it"], "It will never run."),
        E("veeam.repo-offline", "A backup repository is offline.", ["The iSCSI LUN from the Synology is disconnected", "The NAS is down"],
            ["Reconnect the iSCSI target on BK01; rescan the repository in Veeam"], "Every job that writes there fails."),
        E("veeam.repo-full", "A backup repository is filling up.", ["Retention too long for the space"], ["Shorten retention or add space"], "Jobs fail when it is full."),

        E("unifi.offline", "A switch or access point has stopped checking in to the UniFi controller.",
            ["Unplugged, powered off or failed", "Its uplink port is down", "Still pointed at the old (Tenacious-hosted) controller"],
            ["Find it (the evidence gives its model and IP); check its power and uplink", "Re-adopt it to KOR-UNIFI01 if it moved"],
            "Anything plugged into it -- phones, PCs, cameras -- may be offline."),
        E("unifi.firmware", "UniFi devices have firmware updates available.", ["New releases"], ["Update from the controller, a few devices at a time, after hours"],
            "Known bugs and security issues stay unfixed."),
        E("unifi.unnamed", "UniFi devices have no name.", ["Adopted and never named"], ["Name each after where it is (\"Flex - Boardroom\")"],
            "A fault on one says 'USF5P 192.168.1.53' instead of where to walk to."),
        E("unifi.alarms", "The UniFi controller has open alarms.", ["A device fault, a rogue AP, a port flapping"], ["Read them in the controller (Alarm Manager)"], "Whatever the alarm is about."),

        E("net.public-ip", "The office's traffic is leaving by an address other than the Shaw static IP -- or not leaving at all.",
            ["The firewall routing out the wrong WAN (the old bonder)", "The Shaw line down, with traffic failing over"],
            ["Check the Netgate's gateways and default route"], "The VPN, inbound mail (port 25) and every allow-list keyed on the static IP break."),
        E("net.dns", "Name resolution is failing.", ["DC01 (the DNS server) down", "The firewall's DNS forwarders unreachable"], ["Check DC01 and the Netgate's DNS"], "Nothing that uses a name works."),
        E("net.unreachable", "A key address is not answering at all.", ["The line, the firewall or the target is down"], ["Check the Netgate and the Shaw modem"], "No internet, or no route to that target."),
        E("net.loss", "Packets are being lost on the way out.", ["A congested or failing line", "A bad cable or port"], ["Check the Shaw modem and the firewall's WAN port"], "Calls break up, VPN drops, pages stall."),

        E("switch.rebooted", "The core switch restarted recently.", ["A power blip (is it on a UPS outlet?)", "A crash", "A deliberate reboot"],
            ["If nobody rebooted it: check its UPS feed and its logs"], "Every link through it dropped while it restarted."),
        E("switch.port-down", "A core-switch port that was up has gone down.", ["A server, SAN or uplink lost its link", "A cable or SFP failed"],
            ["Find what is on that port; check the cable and SFP"], "Whatever was on that port is cut off (or running on one link instead of two)."),

        E("server.vss-writer", "A VSS writer on this server is in error, so the next backup's snapshot will fail.",
            ["Heavy disk writes during a snapshot, which then left writers timed out (FS01, 30 Sep 2026: three Veeam runs failed)", "A hung service behind the writer"],
            ["Restart the service that hosts the failed writer (vssadmin list writers names it), then re-run the backup", "If writers keep failing: reboot the server"],
            "Backups of this server keep failing until the writer is cleared."),
        E("server.disk-full", "A drive on this server is filling up.", ["Logs, data growth, old updates"], ["Clean up or grow the drive"],
            "Services stop and databases refuse writes when it is full."),
        E("server.service-stopped", "A service set to start automatically is not running on this server.",
            ["It crashed or was stopped and never restarted (APP01's MCP server and certificate renewer, 30 Sep 2026)", "It is retired but still set to Automatic"],
            ["Start it and read its event log for why it stopped", "If it is retired: set it to Disabled so it stops being reported"],
            "Whatever it provides is down -- a stopped certificate renewer means certificates quietly expire."),
        E("server.storage-errors", "The System log shows disk, NTFS or shadow-copy errors in the last day.", ["A failing disk path", "A snapshot aborted (volsnap)"],
            ["Read the events; check the SAN path and the VM's disks"], "Storage errors come before data loss and failed backups."),
        E("server.unpatched", "This server has not installed an update in over 45 days.",
            ["The patching service (T-Net's Ninja) stopped patching servers (every server 71 days on 30 Sep 2026)", "Automatic updates off by policy"],
            ["Patch in a maintenance window: servers one at a time, DC01 last", "Then fix what stopped the patching"], "Every vulnerability fixed since the last update stays open."),
        E("server.reboot-pending", "This server is waiting for a restart to finish installing something.", ["Updates or software that need a restart"],
            ["Restart it in a maintenance window"], "Half-installed updates; some take effect only after the restart."),
        E("ups.on-battery", "The UPS has lost mains and is running on its battery.", ["A power cut", "Its circuit tripped", "Its input cord came out"],
            ["If it is only this UPS: its circuit or cord (the other UPS carries the rack)", "If both: the shutdown chain takes over at 5 minutes"], "When the battery runs out, everything on it drops."),
        E("ups.output-off", "The UPS output is off: everything plugged into it has lost this feed.", ["Turned off", "Overload or fault"], ["Check the UPS front panel"],
            "Dual-fed devices run on one supply; single-fed ones are down."),
        E("ups.bypass", "The UPS is on bypass: mains reaches the load but there is no battery protection.", ["A UPS fault or overload"], ["Check the UPS; clear the fault"],
            "The next blip goes straight through to the servers."),
        E("ups.battery-low", "The UPS battery is low.", ["A long outage", "A worn battery"], ["Shutdown territory: the chain shuts the rack down"], "Hard power loss."),
        // Printers (Rack/PrinterRules, 2026-10-02): supplies by name, and the printer's own error flags.
        E("printer.supply", "An ink, toner, drum, fuser or waste supply in the printer is empty, worn out or full (the finding names it).",
            ["Normal use: it ran out", "A drum or fuser at the end of its rated life", "A waste bin that has filled"],
            ["Fit the part the finding names (the model is on the printer's page)", "Keep one spare of each toner/ink for the busy printers"],
            "The printer stops, or prints faint or streaked pages, until it is replaced."),
        E("printer.jammed", "The printer reports a paper jam.", ["Damp or curled paper", "A worn pickup roller", "The wrong paper type for the tray"],
            ["Open the doors the printer's screen points to and take out the paper"], "Nothing prints on it until the jam is cleared."),
        E("printer.door-open", "A door or cover on the printer is open.", ["Left open after a jam or a toner change"], ["Close it"],
            "Nothing prints on it until it is closed."),
        E("printer.no-paper", "A tray the printer needs is empty.", ["Normal use"], ["Fill the tray the screen names"], "Jobs wait until it is filled."),
        E("printer.no-toner", "The printer says it is out of toner or ink.", ["Normal use"], ["Fit a new cartridge or tank"],
            "Nothing prints, or pages come out blank."),
        E("printer.offline", "The printer has taken itself offline.", ["Someone pressed Offline/Pause", "An error on its screen"],
            ["Look at its screen and put it back online"], "Jobs queue on the PCs and nothing prints."),
        E("printer.service", "The printer is asking for a service call.", ["A hardware fault the printer detected"],
            ["Read the code on its screen and call the service provider with it"], "It may stop printing altogether."),
        E("printer.low-toner", "The printer's own flag says toner or ink is low.", ["Normal use"], ["Order the supply now so it is on hand"],
            "It runs out mid-job."),
        E("printer.low-paper", "The printer says paper is low.", ["Normal use"], ["Top up the trays"], "It runs out mid-job."),
        E("printer.output-full", "The output tray is full.", ["Nobody collected the prints"], ["Empty the tray"], "Printing stops until it is emptied."),
        E("printer.maintenance", "The printer says preventive maintenance is overdue.", ["Page count past the maker's service interval"],
            ["Book the service visit (for the copier: the Canon dealer)"], "More jams and faults as worn parts go on."),
        E("ups.replace-battery", "The UPS asks for a new battery.", ["Age (3-5 years)", "A failed self-test"], ["Order and fit the battery the UPS names"],
            "A dead battery is how the 10 Sep 2026 outage dropped both servers."),
        E("ups.short-runtime", "On a full battery the UPS would last under 15 minutes at the current load.", ["An ageing battery", "More load than before"],
            ["Check the battery age; rebalance the load between the two UPSes"], "Less time for a clean shutdown in an outage."),

        E("agent-silent", "This PC has the NetworkOps agent, and the PC is on, but the agent is not calling in to APP01. Checks fall back to the network route.",
            ["The agent service was stopped or crashed (it restarts itself a minute after a crash, three times a day)", "Something on the PC is blocking it: antivirus, or the firewall to APP01 port 8445",
             "Its key no longer matches (it was reinstalled from somewhere else, or removed)"],
            ["Read C:\\Program Files\\KorOperations\\Agent\\data\\agent.log on the PC (it says why it cannot reach the server)", "Reinstall the agent from this window"],
            "Checks still run over the network while the PC is reachable; when it is off the network at sweep time nothing is learned, and idle time is not read."),
        E("display-sleeps-headless", "This PC runs with no keyboard or mouse, and Windows switches its display off when idle. Only keyboard or mouse input switches it back on, so a monitor plugged in later stays black -- it looks like a dead video output while remote sessions work fine.",
            ["A server-room or compute box (KOR-210, the Perform boxes) left on the default power plan (display off after 15 min)"],
            ["Fix… -> Keep the display on", "For now: plug in a keyboard and press a key, or move the mouse in a remote session"],
            "Whoever plugs in a monitor sees nothing and concludes the graphics card or the cable is dead (KOR-210, 2026-10-01)."),
        E("headless-no-display", "This PC runs with no keyboard or mouse and its graphics card is driving no display at all -- no monitor and no dummy plug on the card. Because KOR Remote mirrors the physical screen, the remote console comes up blank or at a fallback size, and the GPU can sit idle instead of accelerating CAD or rendering.",
            ["A headless workstation (a render, analysis or CAD box, or a Perform box) left with no monitor and no display emulator plugged into its graphics card"],
            ["Plug an HDMI or DisplayPort dummy plug into the card -- match its port (most workstation cards are DisplayPort), and pick a 4K@60 one or run it at 1080p", "Or attach a real monitor to the card"],
            "Anyone connecting over KOR Remote gets a blank or tiny console, and GPU-accelerated work (Revit, ETABS, rendering) can fall back off the card."),
        E("wake-not-ready", "If this PC is shut down, the Wake button cannot start it: something between Windows and the network card stops a magic packet from waking it.",
            ["Fast Startup is on (Windows' default; it was on 29 of 29 KOR PCs on 2026-10-01)", "The network card is not set to wake on a magic packet, or its wake signal (PME) is off",
             "The BIOS has Wake on LAN off, or deep sleep / ErP on (on non-Lenovo PCs NetworkOps cannot read this: a failed wake test is the sign)"],
            ["Fix… -> Turn on Wake-on-LAN (Windows and Lenovo BIOS, remotely)",
             "If it still will not wake after a shutdown: at the console, BIOS -> Power -> Wake on LAN / Power On By PCI-E Enabled, ErP / deep sleep Disabled"],
            "Someone has to walk over and press the power button before it can be patched, checked or used remotely."),
        E("updates-due", "Windows Update has updates waiting on this machine. Nothing installs them by itself: KOR patches on demand, from the Command Center's Updates view.",
            ["A new Patch Tuesday (the second Tuesday of the month) or an out-of-band release", "It was off or not reachable when the last batch was installed",
             "An earlier install failed on it (see its last 'Install updates' run)"],
            ["Updates view: tick it (and any others due), then 'Install' or 'Install and restart if needed'",
             "If an install keeps failing: Repair Windows system files, then install again"],
            "Known, published holes stay open on it; the longer it waits, the more of them there are and the more exploits exist for them."),
        E("mesh-missing", "Remote control (MeshCentral) is not installed on this PC, so the Connect button cannot reach it.",
            ["It was not online when the Mesh agents were installed", "It was rebuilt or reimaged since"],
            ["Install remote control from this window (it goes through the NetworkOps agent, or the network route)"],
            "Nobody can see or work on its screen remotely; support means walking over or an RDP session."),
        E("mesh-silent", "This PC's Mesh agent is installed but not connected to KOR-MESH01, so Connect will fail.",
            ["The Mesh Agent service stopped or crashed", "KOR-MESH01 is down, or the PC cannot reach it on 443", "Its install was removed or damaged"],
            ["Check KOR-MESH01 first if several PCs show this at once", "Otherwise reinstall remote control from this window"],
            "Remote screen and RDP-through-Mesh do not work for this PC until it reconnects."),
        E("agent-outdated", "This PC's NetworkOps agent is older than the version APP01 ships.",
            ["APP01 was updated and this PC has not been reinstalled since"],
            ["Reinstall the agent from this window (reinstalling is the upgrade), or include it in the next rollout"],
            "It keeps working; it just lacks whatever the newer agent fixed."),
    }.ToDictionary(e => e.Family, StringComparer.Ordinal);

    private static KnowledgeEntry E(string family, string meaning, string[] causes, string[] fixes, string ifIgnored)
        => new(family, meaning, causes, fixes, ifIgnored);
}
